/**
 * Baza pytań.
 *
 * Format jednego pytania:
 *   {
 *     id:         unikalny identyfikator (string),
 *     category:   nazwa kategorii pokazywana nad pytaniem,
 *     difficulty: 1-5 (1 = najłatwiejsze),
 *     text:       treść pytania,
 *     answers:    [{ text, correct }] — poprawnych może być kilka!,
 *     note:       krótkie wyjaśnienie pokazywane po odsłonięciu odpowiedzi
 *   }
 *
 * Kolejność odpowiedzi jest losowana w trakcie gry, więc można je tu wpisywać
 * w dowolnym porządku. Aby dorzucić własne pytania, wystarczy dopisać obiekt
 * do tablicy poniżej — reszta gry dostosuje się sama.
 */

export const QUESTIONS = [
  /* ---------------------------- poziom 1 ---------------------------- */
  {
    id: 'geo-canberra',
    category: 'Geografia',
    difficulty: 1,
    text: 'Które miasto jest stolicą Australii?',
    answers: [
      { text: 'Canberra', correct: true },
      { text: 'Sydney' },
      { text: 'Melbourne' },
      { text: 'Perth' },
    ],
    note: 'Canberra została zbudowana jako stolica kompromisowa między rywalizującymi Sydney i Melbourne.',
  },
  {
    id: 'chem-zloto',
    category: 'Nauka',
    difficulty: 1,
    text: 'Jaki jest symbol chemiczny złota?',
    answers: [
      { text: 'Au', correct: true },
      { text: 'Ag' },
      { text: 'Zł' },
      { text: 'Go' },
    ],
    note: 'Au pochodzi od łacińskiego „aurum”. Ag to srebro (argentum).',
  },
  {
    id: 'sport-jedenastu',
    category: 'Sport',
    difficulty: 1,
    text: 'Ilu zawodników jednej drużyny rozpoczyna mecz piłki nożnej na boisku?',
    answers: [
      { text: '11', correct: true },
      { text: '10' },
      { text: '12' },
      { text: '9' },
    ],
    note: 'Dziesięciu zawodników w polu i bramkarz.',
  },
  {
    id: 'mat-kat-prosty',
    category: 'Matematyka',
    difficulty: 1,
    text: 'Ile stopni ma kąt prosty?',
    answers: [
      { text: '90', correct: true },
      { text: '45' },
      { text: '180' },
      { text: '360' },
    ],
    note: 'Kąt półpełny ma 180 stopni, a pełny 360.',
  },
  {
    id: 'sport-kola-olimpijskie',
    category: 'Sport',
    difficulty: 1,
    text: 'Ile kół znajduje się w symbolu olimpijskim?',
    answers: [
      { text: '5', correct: true },
      { text: '4' },
      { text: '6' },
      { text: '3' },
    ],
    note: 'Pięć splecionych kół symbolizuje pięć kontynentów.',
  },
  {
    id: 'tech-www',
    category: 'Technologia',
    difficulty: 1,
    text: 'Co oznacza skrót WWW?',
    answers: [
      { text: 'World Wide Web', correct: true },
      { text: 'Wide World Web' },
      { text: 'World Web Wide' },
      { text: 'Web Without Wires' },
    ],
    note: 'Sieć WWW powstała w CERN-ie na przełomie lat 80. i 90.',
  },

  /* ---------------------------- poziom 2 ---------------------------- */
  {
    id: 'hist-mur-berlinski',
    category: 'Historia',
    difficulty: 2,
    text: 'W którym roku upadł mur berliński?',
    answers: [
      { text: '1989', correct: true },
      { text: '1987' },
      { text: '1990' },
      { text: '1991' },
    ],
    note: 'Przejścia graniczne otwarto w nocy z 9 na 10 listopada 1989 roku.',
  },
  {
    id: 'przyr-najwieksze-zwierze',
    category: 'Przyroda',
    difficulty: 2,
    text: 'Jakie zwierzę jest największe na Ziemi?',
    answers: [
      { text: 'Płetwal błękitny', correct: true },
      { text: 'Słoń afrykański' },
      { text: 'Kaszalot' },
      { text: 'Żyrafa' },
    ],
    note: 'Płetwal błękitny osiąga ponad 25 metrów długości i 150 ton masy.',
  },
  {
    id: 'sztuka-mona-lisa',
    category: 'Sztuka',
    difficulty: 2,
    text: 'Kto namalował „Mona Lisę”?',
    answers: [
      { text: 'Leonardo da Vinci', correct: true },
      { text: 'Michał Anioł' },
      { text: 'Rafael Santi' },
      { text: 'Sandro Botticelli' },
    ],
    note: 'Obraz wisi w paryskim Luwrze.',
  },
  {
    id: 'astro-merkury',
    category: 'Astronomia',
    difficulty: 2,
    text: 'Która planeta krąży najbliżej Słońca?',
    answers: [
      { text: 'Merkury', correct: true },
      { text: 'Wenus' },
      { text: 'Mars' },
      { text: 'Ziemia' },
    ],
    note: 'Merkury okrąża Słońce w niecałe 88 dni.',
  },
  {
    id: 'geo-ottawa',
    category: 'Geografia',
    difficulty: 2,
    text: 'Które miasto jest stolicą Kanady?',
    answers: [
      { text: 'Ottawa', correct: true },
      { text: 'Toronto' },
      { text: 'Montreal' },
      { text: 'Vancouver' },
    ],
    note: 'Toronto jest największym miastem Kanady, ale stolicą jest Ottawa.',
  },
  {
    id: 'geo-baltyk',
    category: 'Geografia',
    difficulty: 2,
    text: 'Nad jakim morzem leży Polska?',
    answers: [
      { text: 'Bałtyckim', correct: true },
      { text: 'Północnym' },
      { text: 'Czarnym' },
      { text: 'Śródziemnym' },
    ],
    note: 'Polskie wybrzeże Bałtyku ma około 440 km długości.',
  },

  /* ---------------------------- poziom 3 ---------------------------- */
  {
    id: 'geo-wolga',
    category: 'Geografia',
    difficulty: 3,
    text: 'Która rzeka jest najdłuższa w Europie?',
    answers: [
      { text: 'Wołga', correct: true },
      { text: 'Dunaj' },
      { text: 'Ren' },
      { text: 'Wisła' },
    ],
    note: 'Wołga liczy ponad 3500 km i uchodzi do Morza Kaspijskiego.',
  },
  {
    id: 'muz-abba',
    category: 'Muzyka',
    difficulty: 3,
    text: 'Z jakiego kraju pochodzi zespół ABBA?',
    answers: [
      { text: 'Szwecja', correct: true },
      { text: 'Norwegia' },
      { text: 'Dania' },
      { text: 'Holandia' },
    ],
    note: 'ABBA wygrała Konkurs Piosenki Eurowizji w 1974 roku utworem „Waterloo”.',
  },
  {
    id: 'lit-pan-tadeusz',
    category: 'Literatura',
    difficulty: 3,
    text: 'Kto napisał „Pana Tadeusza”?',
    answers: [
      { text: 'Adam Mickiewicz', correct: true },
      { text: 'Juliusz Słowacki' },
      { text: 'Henryk Sienkiewicz' },
      { text: 'Bolesław Prus' },
    ],
    note: 'Epopeja narodowa wydana w Paryżu w 1834 roku.',
  },
  {
    id: 'nauka-kosci',
    category: 'Nauka',
    difficulty: 3,
    text: 'Ile kości ma szkielet dorosłego człowieka?',
    answers: [
      { text: '206', correct: true },
      { text: '186' },
      { text: '226' },
      { text: '256' },
    ],
    note: 'Noworodek ma ich około 300 — część zrasta się z wiekiem.',
  },
  {
    id: 'przyr-osmiornica',
    category: 'Przyroda',
    difficulty: 3,
    text: 'Ile serc ma ośmiornica?',
    answers: [
      { text: '3', correct: true },
      { text: '1' },
      { text: '2' },
      { text: '5' },
    ],
    note: 'Dwa serca tłoczą krew do skrzeli, trzecie do reszty ciała.',
  },
  {
    id: 'film-ojciec-chrzestny',
    category: 'Film',
    difficulty: 3,
    text: 'W jakim mieście rozgrywa się większość akcji filmu „Ojciec chrzestny”?',
    answers: [
      { text: 'Nowy Jork', correct: true },
      { text: 'Chicago' },
      { text: 'Las Vegas' },
      { text: 'Boston' },
    ],
    note: 'Rodzina Corleone działa przede wszystkim na nowojorskim Brooklynie i Manhattanie.',
  },
  {
    id: 'hist-1939',
    category: 'Historia',
    difficulty: 3,
    text: 'W którym roku wybuchła II wojna światowa?',
    answers: [
      { text: '1939', correct: true },
      { text: '1938' },
      { text: '1940' },
      { text: '1941' },
    ],
    note: '1 września 1939 roku Niemcy zaatakowały Polskę.',
  },

  /* ---------------------------- poziom 4 ---------------------------- */
  {
    id: 'hist-gagarin',
    category: 'Historia',
    difficulty: 4,
    text: 'Kto jako pierwszy człowiek poleciał w kosmos?',
    answers: [
      { text: 'Jurij Gagarin', correct: true },
      { text: 'Neil Armstrong' },
      { text: 'Alan Shepard' },
      { text: 'John Glenn' },
    ],
    note: 'Lot statku Wostok 1 odbył się 12 kwietnia 1961 roku.',
  },
  {
    id: 'geo-watykan',
    category: 'Geografia',
    difficulty: 4,
    text: 'Które państwo jest najmniejsze na świecie pod względem powierzchni?',
    answers: [
      { text: 'Watykan', correct: true },
      { text: 'Monako' },
      { text: 'Nauru' },
      { text: 'San Marino' },
    ],
    note: 'Watykan zajmuje zaledwie około 0,44 km².',
  },
  {
    id: 'nauka-wodor',
    category: 'Nauka',
    difficulty: 4,
    text: 'Który pierwiastek ma liczbę atomową 1?',
    answers: [
      { text: 'Wodór', correct: true },
      { text: 'Hel' },
      { text: 'Tlen' },
      { text: 'Węgiel' },
    ],
    note: 'Wodór to najlżejszy i najbardziej rozpowszechniony pierwiastek we Wszechświecie.',
  },
  {
    id: 'muz-gitara',
    category: 'Muzyka',
    difficulty: 4,
    text: 'Ile strun ma klasyczna gitara?',
    answers: [
      { text: '6', correct: true },
      { text: '4' },
      { text: '7' },
      { text: '12' },
    ],
    note: 'Cztery struny ma bas, dwanaście — gitara dwunastostrunowa.',
  },
  {
    id: 'sport-mundial',
    category: 'Sport',
    difficulty: 4,
    text: 'Co ile lat odbywają się mistrzostwa świata w piłce nożnej?',
    answers: [
      { text: 'Co 4 lata', correct: true },
      { text: 'Co 2 lata' },
      { text: 'Co 3 lata' },
      { text: 'Co 5 lat' },
    ],
    note: 'Pierwszy mundial rozegrano w Urugwaju w 1930 roku.',
  },
  {
    id: 'przyr-gepard',
    category: 'Przyroda',
    difficulty: 4,
    text: 'Które zwierzę jest najszybsze na lądzie?',
    answers: [
      { text: 'Gepard', correct: true },
      { text: 'Lew' },
      { text: 'Antylopa widłoroga' },
      { text: 'Koń' },
    ],
    note: 'Gepard rozpędza się do około 110 km/h, ale tylko na krótkim dystansie.',
  },
  {
    id: 'hist-moskwa-1980',
    category: 'Historia',
    difficulty: 4,
    text: 'Które miasto było gospodarzem letnich igrzysk olimpijskich w 1980 roku?',
    answers: [
      { text: 'Moskwa', correct: true },
      { text: 'Montreal' },
      { text: 'Los Angeles' },
      { text: 'Monachium' },
    ],
    note: 'Igrzyska w Moskwie zbojkotowała część państw zachodnich.',
  },
  {
    id: 'geo-ameryka-poludniowa',
    category: 'Geografia',
    difficulty: 4,
    text: 'Które z tych państw leżą w Ameryce Południowej?',
    answers: [
      { text: 'Peru', correct: true },
      { text: 'Ekwador', correct: true },
      { text: 'Panama' },
      { text: 'Kuba' },
      { text: 'Kostaryka' },
    ],
    note: 'Panama i Kostaryka to Ameryka Środkowa, a Kuba leży na Karaibach.',
  },

  /* ---------------------------- poziom 5 ---------------------------- */
  {
    id: 'geo-sahara',
    category: 'Geografia',
    difficulty: 5,
    text: 'Która pustynia jest największą gorącą pustynią świata?',
    answers: [
      { text: 'Sahara', correct: true },
      { text: 'Gobi' },
      { text: 'Kalahari' },
      { text: 'Atakama' },
    ],
    note: 'Sahara zajmuje ponad 9 mln km². Największą pustynią w ogóle jest lodowa Antarktyda.',
  },
  {
    id: 'nauka-predkosc-swiatla',
    category: 'Nauka',
    difficulty: 5,
    text: 'Ile w przybliżeniu wynosi prędkość światła w próżni?',
    answers: [
      { text: '300 000 km/s', correct: true },
      { text: '300 000 km/h' },
      { text: '30 000 km/s' },
      { text: '3 000 000 km/s' },
    ],
    note: 'Dokładnie 299 792 458 metrów na sekundę.',
  },
  {
    id: 'muz-sonata-ksiezycowa',
    category: 'Muzyka',
    difficulty: 5,
    text: 'Kto skomponował „Sonatę księżycową”?',
    answers: [
      { text: 'Ludwig van Beethoven', correct: true },
      { text: 'Wolfgang Amadeusz Mozart' },
      { text: 'Fryderyk Chopin' },
      { text: 'Johann Sebastian Bach' },
    ],
    note: 'Sonata fortepianowa nr 14 cis-moll powstała w 1801 roku.',
  },
  {
    id: 'geo-ludnosc',
    category: 'Geografia',
    difficulty: 5,
    text: 'Które państwo ma obecnie najwięcej mieszkańców?',
    answers: [
      { text: 'Indie', correct: true },
      { text: 'Chiny' },
      { text: 'Stany Zjednoczone' },
      { text: 'Indonezja' },
    ],
    note: 'Indie wyprzedziły Chiny w 2023 roku.',
  },
  {
    id: 'hist-titanic',
    category: 'Historia',
    difficulty: 5,
    text: 'W którym roku zatonął Titanic?',
    answers: [
      { text: '1912', correct: true },
      { text: '1905' },
      { text: '1918' },
      { text: '1921' },
    ],
    note: 'Statek zderzył się z górą lodową w nocy z 14 na 15 kwietnia 1912 roku.',
  },
  {
    id: 'tech-cpu',
    category: 'Technologia',
    difficulty: 5,
    text: 'Co oznacza skrót CPU?',
    answers: [
      { text: 'Central Processing Unit', correct: true },
      { text: 'Computer Power Unit' },
      { text: 'Central Program Unit' },
      { text: 'Control Processing Unit' },
    ],
    note: 'Po polsku: centralna jednostka obliczeniowa, czyli procesor.',
  },
  {
    id: 'jez-alfabet',
    category: 'Język',
    difficulty: 5,
    text: 'Ile liter ma polski alfabet?',
    answers: [
      { text: '32', correct: true },
      { text: '26' },
      { text: '35' },
      { text: '30' },
    ],
    note: 'W alfabecie łacińskim jest ich 26 — polski dokłada m.in. ą, ć, ę, ł, ń, ó, ś, ź, ż.',
  },
  {
    id: 'geo-szwajcaria',
    category: 'Geografia',
    difficulty: 5,
    text: 'Które z tych języków są językami urzędowymi Szwajcarii?',
    answers: [
      { text: 'Niemiecki', correct: true },
      { text: 'Francuski', correct: true },
      { text: 'Włoski', correct: true },
      { text: 'Retoromański', correct: true },
      { text: 'Angielski' },
    ],
    note: 'Szwajcaria ma cztery języki urzędowe — angielski nie jest jednym z nich.',
  },
  {
    id: 'astro-pierscienie',
    category: 'Astronomia',
    difficulty: 5,
    text: 'Które z tych planet mają pierścienie?',
    answers: [
      { text: 'Saturn', correct: true },
      { text: 'Jowisz', correct: true },
      { text: 'Uran', correct: true },
      { text: 'Mars' },
      { text: 'Wenus' },
    ],
    note: 'Pierścienie mają wszystkie cztery olbrzymy — poza Saturnem są jednak ledwo widoczne.',
  },
];

export default QUESTIONS;
