/**
 * Baza pytań.
 *
 * Format jednego pytania:
 *   {
 *     id:         unikalny identyfikator (string),
 *     category:   kategoria — gra proponuje przed rundą dwie do wyboru,
 *     difficulty: 1-5 (1 = najłatwiejsze),
 *     text:       treść pytania,
 *     answers:    dokładnie 4 odpowiedzi (tyle jest zapadni), jedna poprawna,
 *     note:       krótkie wyjaśnienie pokazywane po otwarciu zapadni
 *   }
 *
 * Dwie zasady przy układaniu pytań:
 *
 * 1. Wszystkie cztery odpowiedzi mają brzmieć sensownie. Pytanie jest dobre
 *    wtedy, gdy nie da się odsiać trzech błędnych jednym spojrzeniem.
 * 2. Najlepsze pytanie nie sprawdza pamięci, tylko odruch. Pyta o rzecz
 *    pozornie oczywistą, przy której pierwsza myśl prowadzi w bok:
 *    doba na Wenus jest dłuższa niż rok, luty 2100 ma 28 dni, a najbliższym
 *    krewnym hipopotama jest wieloryb.
 *
 * Ponieważ gracz wybiera kategorię, każdy poziom trudności musi mieć pytania
 * w co najmniej kilku kategoriach — pilnuje tego test w tests/engine.test.js.
 */

export const QUESTIONS = [
  /* ============================ poziom 1 ============================ */
  {
    id: 'geo-najdalej-wschod',
    category: 'Geografia',
    difficulty: 1,
    text: 'Które z tych miast leży najdalej na wschód?',
    answers: [
      { text: 'Helsinki', correct: true },
      { text: 'Warszawa' },
      { text: 'Wiedeń' },
      { text: 'Praga' },
    ],
    note: 'Helsinki leżą na 25°E, Warszawa na 21°E. Wiedeń i Praga są jeszcze dalej na zachód niż Warszawa.',
  },
  {
    id: 'hist-123-lata',
    category: 'Historia',
    difficulty: 1,
    text: 'Ile lat Polski nie było na mapie — od trzeciego rozbioru do odzyskania niepodległości?',
    answers: [{ text: '123', correct: true }, { text: '99' }, { text: '111' }, { text: '146' }],
    note: 'Od 1795 do 1918 roku. Liczba 123 weszła do języka jako symbol zaborów.',
  },
  {
    id: 'jez-na-pewno',
    category: 'Język polski',
    difficulty: 1,
    text: 'Który zapis jest poprawny?',
    answers: [
      { text: 'na pewno', correct: true },
      { text: 'napewno' },
      { text: 'na-pewno' },
      { text: 'na pewno się pisze łącznie' },
    ],
    note: 'Zawsze rozdzielnie. „Napewno” to jeden z najczęstszych błędów w polszczyźnie.',
  },
  {
    id: 'nauka-pierze-olow',
    category: 'Nauka',
    difficulty: 1,
    text: 'Co waży więcej: kilogram pierza czy kilogram ołowiu?',
    answers: [
      { text: 'Ważą tyle samo', correct: true },
      { text: 'Ołów' },
      { text: 'Pierze' },
      { text: 'Zależy od objętości' },
    ],
    note: 'Kilogram to kilogram. Różni się objętość, nie masa — i na tym właśnie żeruje to pytanie.',
  },
  {
    id: 'przyr-nogi-pajaka',
    category: 'Przyroda',
    difficulty: 1,
    text: 'Ile PAR nóg ma pająk?',
    answers: [{ text: '4', correct: true }, { text: '3' }, { text: '6' }, { text: '8' }],
    note: 'Osiem nóg, czyli cztery pary. Trzy pary ma owad — i dlatego pająk owadem nie jest.',
  },
  {
    id: 'sport-dogrywka',
    category: 'Sport',
    difficulty: 1,
    text: 'Ile minut trwa dogrywka w meczu piłki nożnej?',
    answers: [{ text: '30', correct: true }, { text: '20' }, { text: '15' }, { text: '45' }],
    note: 'Dwie połowy po 15 minut, bez przerwy na zmianę stron dłuższej niż chwila.',
  },
  {
    id: 'muz-najwiecej-strun',
    category: 'Muzyka',
    difficulty: 1,
    text: 'Który z tych instrumentów ma najwięcej strun?',
    answers: [
      { text: 'Fortepian', correct: true },
      { text: 'Harfa koncertowa' },
      { text: 'Gitara dwunastostrunowa' },
      { text: 'Kontrabas' },
    ],
    note: 'Fortepian ma około 230 strun ukrytych pod pokrywą. Harfa koncertowa — 47.',
  },
  {
    id: 'kult-wiedzmin',
    category: 'Kultura',
    difficulty: 1,
    text: 'Jak nazywa się główny bohater sagi „Wiedźmin”?',
    answers: [
      { text: 'Geralt z Rivii', correct: true },
      { text: 'Jaskier z Oxenfurtu' },
      { text: 'Regis z Dillingen' },
      { text: 'Eskel z Kaer Morhen' },
    ],
    note: 'Pozostali też występują u Sapkowskiego — ale wiedźminem z tytułu jest Geralt.',
  },
  {
    id: 'licz-pol-tuzina',
    category: 'Liczby',
    difficulty: 1,
    text: 'Ile sztuk to pół tuzina?',
    answers: [{ text: '6', correct: true }, { text: '5' }, { text: '10' }, { text: '12' }],
    note: 'Tuzin to 12, więc pół tuzina to 6. Kopa natomiast liczy 60.',
  },
  {
    id: 'kuch-pomidor',
    category: 'Kuchnia',
    difficulty: 1,
    text: 'Które z tych warzyw jest z botanicznego punktu widzenia owocem?',
    answers: [
      { text: 'Pomidor', correct: true },
      { text: 'Marchew' },
      { text: 'Burak' },
      { text: 'Ziemniak' },
    ],
    note: 'Pomidor to jagoda — powstaje z zalążni kwiatu. Pozostałe trzy to korzenie i bulwy.',
  },

  /* ============================ poziom 2 ============================ */
  {
    id: 'geo-dunaj',
    category: 'Geografia',
    difficulty: 2,
    text: 'Przez które z tych państw NIE przepływa Dunaj?',
    answers: [
      { text: 'Czechy', correct: true },
      { text: 'Austria' },
      { text: 'Węgry' },
      { text: 'Serbia' },
    ],
    note: 'Dunaj mija Czechy bokiem — płynie przez dziesięć państw, ale nie przez to.',
  },
  {
    id: 'hist-co-najwczesniej',
    category: 'Historia',
    difficulty: 2,
    text: 'Który z tych wynalazków powstał najwcześniej?',
    answers: [
      { text: 'Maszyna do pisania', correct: true },
      { text: 'Telefon' },
      { text: 'Żarówka' },
      { text: 'Samochód' },
    ],
    note: 'Maszyna do pisania 1868, telefon 1876, żarówka 1879, samochód 1886. Kolejność bywa zaskoczeniem.',
  },
  {
    id: 'jez-musztarda',
    category: 'Język polski',
    difficulty: 2,
    text: 'Co znaczy powiedzenie „musztarda po obiedzie”?',
    answers: [
      { text: 'Coś, co przychodzi stanowczo za późno', correct: true },
      { text: 'Dodatek, bez którego można się obejść' },
      { text: 'Przesada w drobnej sprawie' },
      { text: 'Niespodziewany zwrot na koniec' },
    ],
    note: 'Musztarda podana po posiłku nie ma już czego przyprawić.',
  },
  {
    id: 'nauka-kostka',
    category: 'Nauka',
    difficulty: 2,
    text: 'Ile wynosi suma oczek na dwóch przeciwległych ścianach kostki do gry?',
    answers: [{ text: '7', correct: true }, { text: '6' }, { text: '8' }, { text: '9' }],
    note: 'Zawsze 7: naprzeciw jedynki leży szóstka, naprzeciw dwójki piątka, naprzeciw trójki czwórka.',
  },
  {
    id: 'przyr-hipopotam',
    category: 'Przyroda',
    difficulty: 2,
    text: 'Które z tych zwierząt jest najbliżej spokrewnione z hipopotamem?',
    answers: [
      { text: 'Wieloryb', correct: true },
      { text: 'Świnia' },
      { text: 'Nosorożec' },
      { text: 'Słoń' },
    ],
    note: 'Walenie i hipopotamy mają wspólnego przodka. Podobieństwo do nosorożca jest wyłącznie z wyglądu.',
  },
  {
    id: 'kuch-jaglana',
    category: 'Kuchnia',
    difficulty: 2,
    text: 'Z jakiego zboża produkuje się kaszę jaglaną?',
    answers: [
      { text: 'Z prosa', correct: true },
      { text: 'Z jęczmienia' },
      { text: 'Z owsa' },
      { text: 'Z gryki' },
    ],
    note: 'Jaglana to obłuskane proso. Z jęczmienia jest pęczak i perłowa, z gryki — gryczana.',
  },
  {
    id: 'muz-hymn-ue',
    category: 'Muzyka',
    difficulty: 2,
    text: 'Hymn Unii Europejskiej to fragment…',
    answers: [
      { text: 'IX Symfonii Beethovena', correct: true },
      { text: 'V Symfonii Beethovena' },
      { text: '„Wodnej muzyki” Händla' },
      { text: '„Czterech pór roku” Vivaldiego' },
    ],
    note: '„Oda do radości” z finału IX Symfonii — przyjęta bez słów, żeby żaden język nie był uprzywilejowany.',
  },
  {
    id: 'sport-400m',
    category: 'Sport',
    difficulty: 2,
    text: 'Ile okrążeń stadionowej bieżni liczy bieg na 400 metrów?',
    answers: [{ text: '1', correct: true }, { text: '2' }, { text: '4' }, { text: 'Pół' }],
    note: 'Standardowa bieżnia ma dokładnie 400 metrów, więc to jedno okrążenie.',
  },
  {
    id: 'licz-miliard',
    category: 'Liczby',
    difficulty: 2,
    text: 'Ile zer ma miliard zapisany cyframi?',
    answers: [{ text: '9', correct: true }, { text: '6' }, { text: '12' }, { text: '8' }],
    note: '1 000 000 000 — dziewięć zer. Sześć ma milion, dwanaście bilion.',
  },
  {
    id: 'lit-saba',
    category: 'Literatura',
    difficulty: 2,
    text: 'Jak nazywał się pies ze „W pustyni i w puszczy”?',
    answers: [{ text: 'Saba', correct: true }, { text: 'Kali' }, { text: 'Mea' }, { text: 'Nel' }],
    note: 'Saba to dog. Kali i Mea to towarzysze podróży, a Nel — mała bohaterka powieści.',
  },

  /* ============================ poziom 3 ============================ */
  {
    id: 'geo-rownik',
    category: 'Geografia',
    difficulty: 3,
    text: 'Które z tych miast leży najbliżej równika?',
    answers: [
      { text: 'Kair', correct: true },
      { text: 'Tokio' },
      { text: 'Nowy Jork' },
      { text: 'Rzym' },
    ],
    note: 'Kair leży na 30°N, Tokio na 36°N, Nowy Jork na 41°N, Rzym na 42°N.',
  },
  {
    id: 'hist-najdluzej-krol',
    category: 'Historia',
    difficulty: 3,
    text: 'Który z tych władców panował w Polsce najdłużej?',
    answers: [
      { text: 'Władysław Jagiełło', correct: true },
      { text: 'Zygmunt III Waza' },
      { text: 'Zygmunt Stary' },
      { text: 'Kazimierz Wielki' },
    ],
    note: 'Jagiełło 48 lat, Zygmunt III Waza 45, Zygmunt Stary 42, Kazimierz Wielki 37.',
  },
  {
    id: 'jez-rak',
    category: 'Język polski',
    difficulty: 3,
    text: 'Jak brzmi dopełniacz liczby mnogiej słowa „ręka”?',
    answers: [{ text: 'rąk', correct: true }, { text: 'ręk' }, { text: 'ręków' }, { text: 'rąków' }],
    note: 'Nie ma rąk. Wymiana „ę” na „ą” jest tu regularna, choć brzmi jak wyjątek.',
  },
  {
    id: 'nauka-wenus',
    category: 'Nauka',
    difficulty: 3,
    text: 'Jak ma się doba na Wenus do jej roku?',
    answers: [
      { text: 'Doba jest dłuższa niż rok', correct: true },
      { text: 'Rok jest dwa razy dłuższy' },
      { text: 'Są prawie równe' },
      { text: 'Doba trwa niecałe 24 godziny' },
    ],
    note: 'Wenus obraca się wokół osi 243 dni ziemskich, a Słońce okrąża w 225. Dzień trwa tam dłużej niż rok.',
  },
  {
    id: 'przyr-banan',
    category: 'Przyroda',
    difficulty: 3,
    text: 'Na czym rosną banany?',
    answers: [
      { text: 'Na roślinie zielnej — bananowiec nie jest drzewem', correct: true },
      { text: 'Na drzewie z twardym pniem' },
      { text: 'Na krzewie' },
      { text: 'Na pnączu' },
    ],
    note: 'To, co wygląda na pień, jest zwiniętymi liśćmi. Botanicznie bananowiec to bylina, a banan — jagoda.',
  },
  {
    id: 'kuch-al-dente',
    category: 'Kuchnia',
    difficulty: 3,
    text: 'Co oznacza „al dente”?',
    answers: [
      { text: 'Makaron stawia jeszcze lekki opór przy gryzieniu', correct: true },
      { text: 'Makaron gotowany w osolonej wodzie' },
      { text: 'Makaron podany od razu po odcedzeniu' },
      { text: 'Makaron przelany zimną wodą' },
    ],
    note: 'Dosłownie „na ząb”. Środek nitki jest jeszcze odrobinę twardy — i o to chodzi.',
  },
  {
    id: 'muz-pianino',
    category: 'Muzyka',
    difficulty: 3,
    text: 'Ile klawiszy ma standardowe pianino?',
    answers: [{ text: '88', correct: true }, { text: '76' }, { text: '61' }, { text: '96' }],
    note: '52 białe i 36 czarnych. 61 i 76 to typowe rozmiary keyboardów.',
  },
  {
    id: 'sport-golf',
    category: 'Sport',
    difficulty: 3,
    text: 'Ile dołków ma standardowe pole golfowe?',
    answers: [{ text: '18', correct: true }, { text: '12' }, { text: '16' }, { text: '24' }],
    note: 'Osiemnaście — układ przyjęty w XVIII wieku w szkockim St Andrews.',
  },
  {
    id: 'lit-nobelisci',
    category: 'Literatura',
    difficulty: 3,
    text: 'Ilu Polaków otrzymało do tej pory literacką Nagrodę Nobla?',
    answers: [{ text: '5', correct: true }, { text: '3' }, { text: '4' }, { text: '6' }],
    note: 'Sienkiewicz, Reymont, Miłosz, Szymborska i Tokarczuk.',
  },
  {
    id: 'licz-doba',
    category: 'Liczby',
    difficulty: 3,
    text: 'Ile minut ma doba?',
    answers: [
      { text: '1440', correct: true },
      { text: '1240' },
      { text: '1200' },
      { text: '1660' },
    ],
    note: '24 razy 60. Sekund w dobie jest już 86 400.',
  },

  /* ============================ poziom 4 ============================ */
  {
    id: 'geo-kaspijskie',
    category: 'Geografia',
    difficulty: 4,
    text: 'Czym w rzeczywistości jest Morze Kaspijskie?',
    answers: [
      { text: 'Największym jeziorem świata', correct: true },
      { text: 'Zatoką Oceanu Indyjskiego' },
      { text: 'Morzem wewnętrznym połączonym z Morzem Czarnym' },
      { text: 'Sztucznym zbiornikiem z czasów ZSRR' },
    ],
    note: 'Nie ma połączenia z oceanem, więc mimo nazwy i zasolenia jest jeziorem — i to największym.',
  },
  {
    id: 'hist-wright-ksiezyc',
    category: 'Historia',
    difficulty: 4,
    text: 'Ile lat dzieli pierwszy lot braci Wright od lądowania człowieka na Księżycu?',
    answers: [{ text: '66', correct: true }, { text: '46' }, { text: '86' }, { text: '106' }],
    note: 'Od 1903 do 1969 roku. Ludzie, którzy widzieli pierwszy samolot, dożyli lądowania na Księżycu.',
  },
  {
    id: 'jez-lakoniczny',
    category: 'Język polski',
    difficulty: 4,
    text: 'Co znaczy „lakoniczny”?',
    answers: [
      { text: 'Zwięzły, powiedziany w kilku słowach', correct: true },
      { text: 'Rozwlekły i pełen dygresji' },
      { text: 'Chłodny, pozbawiony emocji' },
      { text: 'Zawiły i trudny do zrozumienia' },
    ],
    note: 'Od Lakonii, czyli Sparty — jej mieszkańcy słynęli z odpowiadania jednym zdaniem.',
  },
  {
    id: 'nauka-powietrze',
    category: 'Nauka',
    difficulty: 4,
    text: 'Którego gazu jest najwięcej w powietrzu, którym oddychamy?',
    answers: [
      { text: 'Azotu', correct: true },
      { text: 'Tlenu' },
      { text: 'Dwutlenku węgla' },
      { text: 'Argonu' },
    ],
    note: 'Azot to 78 procent, tlen tylko 21. Argon jest trzeci, a dwutlenku węgla jest ułamek procenta.',
  },
  {
    id: 'przyr-osmiornica',
    category: 'Przyroda',
    difficulty: 4,
    text: 'Ile serc ma ośmiornica?',
    answers: [{ text: '3', correct: true }, { text: '1' }, { text: '2' }, { text: '5' }],
    note: 'Dwa tłoczą krew do skrzeli, trzecie do reszty ciała. Przy pływaniu to główne przestaje bić.',
  },
  {
    id: 'film-oscar-ida',
    category: 'Film',
    difficulty: 4,
    text: 'Który polski film zdobył Oscara dla najlepszego filmu nieanglojęzycznego?',
    answers: [
      { text: '„Ida”', correct: true },
      { text: '„Zimna wojna”' },
      { text: '„Katyń”' },
      { text: '„Boże Ciało”' },
    ],
    note: '„Ida” Pawła Pawlikowskiego wygrała w 2015 roku. Pozostałe trzy były nominowane, ale bez statuetki.',
  },
  {
    id: 'sport-malysz',
    category: 'Sport',
    difficulty: 4,
    text: 'Który polski skoczek jako pierwszy wygrał Turniej Czterech Skoczni?',
    answers: [
      { text: 'Adam Małysz', correct: true },
      { text: 'Kamil Stoch' },
      { text: 'Wojciech Fortuna' },
      { text: 'Piotr Żyła' },
    ],
    note: 'Małysz wygrał w sezonie 2000/2001. Stoch powtórzył to dopiero w 2017/2018.',
  },
  {
    id: 'lit-ferdydurke',
    category: 'Literatura',
    difficulty: 4,
    text: 'Kto napisał „Ferdydurke”?',
    answers: [
      { text: 'Witold Gombrowicz', correct: true },
      { text: 'Bruno Schulz' },
      { text: 'Stanisław Ignacy Witkiewicz' },
      { text: 'Zofia Nałkowska' },
    ],
    note: 'Gombrowicz, 1937. Wszyscy czterej tworzyli w tym samym dwudziestoleciu.',
  },
  {
    id: 'licz-luty-2100',
    category: 'Liczby',
    difficulty: 4,
    text: 'Ile dni będzie miał luty w roku 2100?',
    answers: [{ text: '28', correct: true }, { text: '29' }, { text: '30' }, { text: '27' }],
    note: 'Rok podzielny przez 100 nie jest przestępny — chyba że dzieli się przez 400. Rok 2000 był, 2100 nie będzie.',
  },
  {
    id: 'kuch-czekolada',
    category: 'Kuchnia',
    difficulty: 4,
    text: 'Z czego powstaje biała czekolada?',
    answers: [
      { text: 'Z masła kakaowego, bez miazgi kakaowej', correct: true },
      { text: 'Z kakao odbarwionego chemicznie' },
      { text: 'Z mleka w proszku i cukru, bez składników kakaowych' },
      { text: 'Z ziaren kakaowca zbieranych przed dojrzeniem' },
    ],
    note: 'Zawiera tłuszcz z ziarna, ale nie zawiera miazgi — stąd brak brązowego koloru i gorzkiego smaku.',
  },

  /* ============================ poziom 5 ============================ */
  {
    id: 'geo-poludniowa-polkula',
    category: 'Geografia',
    difficulty: 5,
    text: 'Które z tych państw leży w całości na półkuli południowej?',
    answers: [
      { text: 'Australia', correct: true },
      { text: 'Brazylia' },
      { text: 'Kenia' },
      { text: 'Ekwador' },
    ],
    note: 'Równik przecina Brazylię, Kenię i — co słychać już w nazwie — Ekwador.',
  },
  {
    id: 'hist-uj',
    category: 'Historia',
    difficulty: 5,
    text: 'W którym roku założono Uniwersytet Jagielloński?',
    answers: [{ text: '1364', correct: true }, { text: '1264' }, { text: '1400' }, { text: '1464' }],
    note: 'Kazimierz Wielki, 1364. W 1400 roku Władysław Jagiełło uczelnię odnowił — stąd druga data w obiegu.',
  },
  {
    id: 'jez-gilotyna',
    category: 'Język polski',
    difficulty: 5,
    text: 'Które z tych słów pochodzi od nazwiska?',
    answers: [
      { text: 'Gilotyna', correct: true },
      { text: 'Parasol' },
      { text: 'Kanapka' },
      { text: 'Firanka' },
    ],
    note: 'Od Josepha Guillotina, który maszyny nie wynalazł — postulował tylko, by egzekucje były szybkie.',
  },
  {
    id: 'nauka-masa-slonca',
    category: 'Nauka',
    difficulty: 5,
    text: 'Jaką część masy Układu Słonecznego stanowi samo Słońce?',
    answers: [
      { text: 'Ponad 99 procent', correct: true },
      { text: 'Około 70 procent' },
      { text: 'Około 85 procent' },
      { text: 'Około 95 procent' },
    ],
    note: '99,86 procent. Cała reszta — planety, księżyce, planetoidy — mieści się w tym, co zostało.',
  },
  {
    id: 'przyr-miod',
    category: 'Przyroda',
    difficulty: 5,
    text: 'Dlaczego miód praktycznie się nie psuje?',
    answers: [
      { text: 'Jest kwaśny i niemal pozbawiony wody, więc bakterie w nim nie żyją', correct: true },
      { text: 'Zawiera naturalny antybiotyk wytwarzany przez pszczoły' },
      { text: 'Jest sterylny, bo pszczoły podgrzewają go w ulu' },
      { text: 'Cukry w miodzie nie ulegają rozkładowi' },
    ],
    note: 'W grobowcach egipskich znaleziono miód sprzed tysięcy lat, wciąż zdatny do jedzenia.',
  },
  {
    id: 'kuch-szafran',
    category: 'Kuchnia',
    difficulty: 5,
    text: 'Czym jest szafran, najdroższa przyprawa świata?',
    answers: [
      { text: 'Znamionami kwiatu krokusa, zbieranymi ręcznie', correct: true },
      { text: 'Sproszkowaną korą drzewa szafranowego' },
      { text: 'Suszonym korzeniem odmiany kurkumy' },
      { text: 'Pyłkiem zbieranym z kwiatów przez pszczoły' },
    ],
    note: 'Każdy kwiat daje trzy nitki. Na kilogram przyprawy trzeba ich około 150 tysięcy — stąd cena.',
  },
  {
    id: 'film-rejs',
    category: 'Film',
    difficulty: 5,
    text: 'Kto wyreżyserował „Rejs”?',
    answers: [
      { text: 'Marek Piwowski', correct: true },
      { text: 'Stanisław Bareja' },
      { text: 'Juliusz Machulski' },
      { text: 'Andrzej Kondratiuk' },
    ],
    note: 'Bareja nakręcił „Misia” i „Alternatywy 4” — „Rejs” to jednak Piwowski.',
  },
  {
    id: 'sport-maraton',
    category: 'Sport',
    difficulty: 5,
    text: 'Skąd wzięła się dziwna długość maratonu — 42,195 km?',
    answers: [
      { text: 'Z igrzysk w Londynie, gdzie trasę wydłużono do loży królewskiej', correct: true },
      { text: 'To dokładna odległość z Maratonu do Aten' },
      { text: 'Zaokrąglono ją z 26 mil angielskich' },
      { text: 'Wyznaczono ją losowo na pierwszych igrzyskach w 1896 roku' },
    ],
    note: 'Londyn 1908: start pod oknami zamku w Windsorze, meta przed lożą królewską. Od 1921 roku to obowiązujący dystans.',
  },
  {
    id: 'lit-hanna-krall',
    category: 'Literatura',
    difficulty: 5,
    text: 'Kto napisał „Zdążyć przed Panem Bogiem”?',
    answers: [
      { text: 'Hanna Krall', correct: true },
      { text: 'Ryszard Kapuściński' },
      { text: 'Marek Edelman' },
      { text: 'Wisława Szymborska' },
    ],
    note: 'To zapis rozmowy Hanny Krall z Markiem Edelmanem — on jest bohaterem książki, nie jej autorem.',
  },
  {
    id: 'licz-dwa-do-dziesiatej',
    category: 'Liczby',
    difficulty: 5,
    text: 'Ile wynosi dwa do potęgi dziesiątej?',
    answers: [
      { text: '1024', correct: true },
      { text: '1000' },
      { text: '2048' },
      { text: '512' },
    ],
    note: 'Dlatego kilobajt to przez lata było 1024 bajty, a nie równe tysiąc.',
  },
];

export default QUESTIONS;
