/**
 * Baza pytań.
 *
 * Format jednego pytania:
 *   {
 *     id:         unikalny identyfikator,
 *     label:      HASŁO — nazwa, którą gracz widzi przy wyborze. Nigdy nie jest
 *                 nazwą dziedziny; sens ma się rozjaśnić dopiero po pytaniu,
 *     category:   prawdziwa dziedzina, ujawniana razem z rozwiązaniem,
 *     difficulty: 1 = nadaje się na rozgrzewkę (pierwsza runda losuje tylko
 *                 takie). Wyższe wartości są tylko wskazówką dla autora —
 *                 gra traktuje całą resztę puli jednakowo,
 *     text:       treść pytania,
 *     answers:    cztery odpowiedzi; jedna `correct`, jedna `rival`,
 *     note:       jedno zdanie wyjaśnienia po otwarciu zapadni
 *   }
 *
 * Trzy zasady, na których stoi ta baza:
 *
 * 1. `rival` to najpoważniejszy kontrkandydat — odpowiedź, w którą wpada
 *    dobrze poinformowany gracz. W rundach z trzema i dwiema zapadniami gra
 *    odrzuca odpowiedzi, ale tę zostawia zawsze. Bez niej finał robiłby się
 *    banalny, gdyby na placu boju został przypadkiem oczywisty odsiew.
 *
 * 2. Pytanie ma wciągać w DWIE odpowiedzi, nie w jedną. Układ jest zawsze
 *    ten sam: jedna poprawna, jedna prawie poprawna i dwa odsiewy. Dopiero
 *    wtedy dzielenie pieniędzy między zapadnie ma sens — a o to w tej grze chodzi.
 *
 * 3. Żadnych faktów z terminem ważności. Aktualni rekordziści, urzędujący
 *    politycy i bieżące rankingi są zakazane: w teleturnieju najgłośniejszą
 *    wpadką było pytanie o najdłuższe metro poza Chinami, gdzie w 2020 roku
 *    poprawny był Londyn, a w 2023 — już Moskwa.
 *
 * `spoken` przy odpowiedzi albo pytaniu podaje wersję do przeczytania na głos
 * (lektor czyta „tysiąc czterysta dziesięć”, gracz widzi „1410”).
 */

export const QUESTIONS = [
  /* ===================== rozgrzewka (runda pierwsza) ===================== */
  {
    id: 'geo-sasiedzi',
    label: 'Dwa bratanki',
    category: 'Geografia',
    difficulty: 1,
    text: 'Które z tych państw NIE graniczy z Polską?',
    answers: [
      { text: 'Węgry', correct: true },
      { text: 'Litwa', rival: true },
      { text: 'Słowacja' },
      { text: 'Czechy' },
    ],
    note: 'Mimo przysłowia o dwóch bratankach wspólnej granicy z Węgrami nie ma — rozdziela nas Słowacja.',
  },
  {
    id: 'geo-canberra',
    label: 'Stolice świata',
    category: 'Geografia',
    difficulty: 1,
    text: 'Stolicą Australii jest:',
    answers: [
      { text: 'Canberra', correct: true },
      { text: 'Sydney', rival: true },
      { text: 'Melbourne' },
      { text: 'Brisbane' },
    ],
    note: 'Canberrę zbudowano od zera właśnie po to, by zakończyć spór Sydney i Melbourne o miano stolicy.',
  },
  {
    id: 'geo-srodziemne',
    label: 'Nad wodą',
    category: 'Geografia',
    difficulty: 1,
    text: 'Które z tych państw NIE ma dostępu do Morza Śródziemnego?',
    answers: [
      { text: 'Portugalia', correct: true },
      { text: 'Chorwacja', rival: true },
      { text: 'Hiszpania' },
      { text: 'Grecja' },
    ],
    note: 'Cała portugalska linia brzegowa wychodzi na Ocean Atlantycki — Morze Śródziemne zaczyna się dopiero za Gibraltarem.',
  },
  {
    id: 'hist-grunwald',
    label: 'Dwa miecze',
    category: 'Historia',
    difficulty: 1,
    text: 'Bitwa pod Grunwaldem została stoczona w roku:',
    answers: [
      { text: '1410', spoken: 'tysiąc czterysta dziesięć', correct: true },
      { text: '1409', spoken: 'tysiąc czterysta dziewięć', rival: true },
      { text: '1385', spoken: 'tysiąc trzysta osiemdziesiąt pięć' },
      { text: '1466', spoken: 'tysiąc czterysta sześćdziesiąt sześć' },
    ],
    note: 'Rok wcześniej wybuchła dopiero wielka wojna z zakonem; pozostałe daty to unia w Krewie i drugi pokój toruński.',
  },
  {
    id: 'hist-pierwszy-krol',
    label: 'Piastowie',
    category: 'Historia',
    difficulty: 1,
    text: 'Pierwszym koronowanym królem Polski był:',
    answers: [
      { text: 'Bolesław Chrobry', correct: true },
      { text: 'Mieszko I', spoken: 'Mieszko pierwszy', rival: true },
      { text: 'Władysław Łokietek' },
      { text: 'Kazimierz Wielki' },
    ],
    note: 'Mieszko I był księciem i nigdy nie przyjął korony — zrobił to jego syn tuż przed śmiercią, w 1025 roku.',
  },
  {
    id: 'pol-rekawica',
    label: 'Powiedzonka',
    category: 'Język polski',
    difficulty: 1,
    text: 'Co znaczy zwrot „rzucić komuś rękawicę”?',
    answers: [
      { text: 'Wyzwać go do walki', correct: true },
      { text: 'Przyznać się przed nim do porażki', rival: true },
      { text: 'Pogodzić się z nim' },
      { text: 'Poprosić go o pomoc' },
    ],
    note: 'Poddanie się to „rzucić ręcznik”, a rękawicę rzucali sobie rycerze na znak wyzwania na pojedynek.',
  },
  {
    id: 'pol-enigmatyczny',
    label: 'Obce słowa',
    category: 'Język polski',
    difficulty: 1,
    text: 'Słowo „enigmatyczny” znaczy tyle co:',
    answers: [
      { text: 'tajemniczy', correct: true },
      { text: 'energiczny', rival: true },
      { text: 'kłamliwy' },
      { text: 'ogromny' },
    ],
    note: 'Podobieństwo brzmienia do „energiczny” to pułapka — słowo pochodzi od greckiego „ainigma”, czyli zagadka.',
  },
  {
    id: 'pol-filatelista',
    label: 'Na kopercie',
    category: 'Język polski',
    difficulty: 1,
    text: 'Czym zajmuje się filatelista?',
    answers: [
      { text: 'Zbiera znaczki pocztowe', correct: true },
      { text: 'Zbiera pocztówki', rival: true },
      { text: 'Zbiera monety' },
      { text: 'Zbiera stare mapy' },
    ],
    note: 'Monety zbiera numizmatyk, a pocztówki — deltiolog; filatelistyka to znaczki i wszystko, co pocztowe.',
  },
  {
    id: 'nauka-trojkat',
    label: 'Figury',
    category: 'Nauka',
    difficulty: 1,
    text: 'Jak nazywa się trójkąt, którego wszystkie boki mają różną długość?',
    answers: [
      { text: 'różnoboczny', correct: true },
      { text: 'równoramienny', rival: true },
      { text: 'równoboczny' },
      { text: 'prostokątny' },
    ],
    note: 'Nazwy „równoramienny” i „równoboczny” zapadają w pamięć ze szkoły mocniej niż ta czwarta, najzwyklejsza możliwość.',
  },
  {
    id: 'nauka-azot',
    label: 'Pełną piersią',
    category: 'Nauka',
    difficulty: 1,
    text: 'Który gaz stanowi największą część powietrza atmosferycznego?',
    answers: [
      { text: 'azot', correct: true },
      { text: 'tlen', rival: true },
      { text: 'dwutlenek węgla' },
      { text: 'wodór' },
    ],
    note: 'Azotu jest w powietrzu około 78 procent, a tlenu — o którym myślimy najpierw — tylko 21.',
  },
  {
    id: 'przyr-rekin',
    label: 'Mleko matki',
    category: 'Przyroda',
    difficulty: 1,
    text: 'Które z tych zwierząt NIE jest ssakiem?',
    answers: [
      { text: 'rekin', correct: true },
      { text: 'delfin', rival: true },
      { text: 'nietoperz' },
      { text: 'wieloryb' },
    ],
    note: 'Rekin jest rybą i oddycha skrzelami, podczas gdy delfin i wieloryb wypływają po powietrze, a nietoperz karmi młode mlekiem.',
  },
  {
    id: 'przyr-modrzew',
    label: 'Drzewa',
    category: 'Przyroda',
    difficulty: 1,
    text: 'Które z tych drzew iglastych zrzuca igły na zimę?',
    answers: [
      { text: 'modrzew', correct: true },
      { text: 'sosna', rival: true },
      { text: 'świerk' },
      { text: 'jodła' },
    ],
    note: 'Modrzew to jedyne rodzime drzewo iglaste, które jesienią żółknie i całkiem się ogołaca.',
  },
  {
    id: 'muz-gitara',
    label: 'Instrumenty',
    category: 'Muzyka',
    difficulty: 1,
    text: 'Ile strun ma klasyczna gitara?',
    answers: [
      { text: '6', spoken: 'sześć', correct: true },
      { text: '4', spoken: 'cztery', rival: true },
      { text: '7', spoken: 'siedem' },
      { text: '12', spoken: 'dwanaście' },
    ],
    note: 'Cztery struny ma gitara basowa, a dwanaście — odmiana dwunastostrunowa, w której struny biegną parami.',
  },
  {
    id: 'muz-vivaldi',
    label: 'Kompozytorzy',
    category: 'Muzyka',
    difficulty: 1,
    text: 'Cykl koncertów skrzypcowych „Cztery pory roku” skomponował:',
    answers: [
      { text: 'Antonio Vivaldi', correct: true },
      { text: 'Johann Sebastian Bach', rival: true },
      { text: 'Wolfgang Amadeusz Mozart' },
      { text: 'Ludwig van Beethoven' },
    ],
    note: 'Vivaldi napisał ten cykl w epoce baroku, mniej więcej wtedy, gdy tworzył Bach — stąd najczęstsza pomyłka.',
  },
  {
    id: 'kult-gronostaj',
    label: 'Muzea',
    category: 'Kultura',
    difficulty: 1,
    text: 'W którym polskim mieście na stałe znajduje się „Dama z gronostajem” Leonarda da Vinci?',
    answers: [
      { text: 'Kraków', correct: true },
      { text: 'Warszawa', rival: true },
      { text: 'Wrocław' },
      { text: 'Poznań' },
    ],
    note: 'Obraz należy do kolekcji Czartoryskich i wisi w Krakowie, choć odruchowo szuka się najcenniejszych dzieł w stolicy.',
  },
  {
    id: 'film-pianista',
    label: 'Reżyserzy',
    category: 'Film',
    difficulty: 1,
    text: 'Nagrodzony Oscarem film „Pianista” wyreżyserował:',
    answers: [
      { text: 'Roman Polański', correct: true },
      { text: 'Andrzej Wajda', rival: true },
      { text: 'Krzysztof Kieślowski' },
      { text: 'Jerzy Hoffman' },
    ],
    note: 'Polański, sam ocalały z krakowskiego getta, odebrał za „Pianistę” Oscara za reżyserię w 2003 roku.',
  },
  {
    id: 'film-kiler',
    label: 'Nie ten człowiek',
    category: 'Film',
    difficulty: 1,
    text: 'Kto zagrał tytułową rolę w komedii Juliusza Machulskiego „Kiler”?',
    answers: [
      { text: 'Cezary Pazura', correct: true },
      { text: 'Jerzy Stuhr', rival: true },
      { text: 'Marek Kondrat' },
      { text: 'Bogusław Linda' },
    ],
    note: 'Jerzy Stuhr rzeczywiście gra w tym filmie — ale Siarę, nie taksówkarza wziętego za płatnego mordercę.',
  },
  {
    id: 'lit-muszkieterowie',
    label: 'Jeden za wszystkich',
    category: 'Literatura',
    difficulty: 1,
    text: 'Który z bohaterów Aleksandra Dumasa NIE należał do tytułowej trójki „Trzech muszkieterów”?',
    answers: [
      { text: "d'Artagnan", spoken: 'Dartanian', correct: true },
      { text: 'Aramis', rival: true },
      { text: 'Atos' },
      { text: 'Portos' },
    ],
    note: 'Główny bohater dopiero na kartach powieści dołącza do muszkieterów, więc tytułową trójkę tworzą pozostali trzej.',
  },
  {
    id: 'lit-inwokacja',
    label: 'Wieszczowie',
    category: 'Literatura',
    difficulty: 1,
    text: 'Słowa „Litwo, Ojczyzno moja!” rozpoczynają utwór, którego autorem jest:',
    answers: [
      { text: 'Adam Mickiewicz', correct: true },
      { text: 'Juliusz Słowacki', rival: true },
      { text: 'Cyprian Kamil Norwid' },
      { text: 'Jan Kochanowski' },
    ],
    note: 'To inwokacja „Pana Tadeusza”; Słowacki, również wieszcz i również z Kresów, napisał „Balladynę” i „Kordiana”.',
  },
  {
    id: 'sport-siatkowka-boisko',
    label: 'Gry zespołowe',
    category: 'Sport',
    difficulty: 1,
    text: 'Ilu zawodników jednej drużyny przebywa na boisku podczas meczu siatkówki?',
    answers: [
      { text: '6', spoken: 'sześciu', correct: true },
      { text: '5', spoken: 'pięciu', rival: true },
      { text: '7', spoken: 'siedmiu' },
      { text: '11', spoken: 'jedenastu' },
    ],
    note: 'Pięciu gra w koszykówce, siedmiu w piłce ręcznej, a w siatkówce sześciu ustawia się w dwóch liniach po trzech.',
  },
  {
    id: 'sport-wimbledon',
    label: 'Zielono mi',
    category: 'Sport',
    difficulty: 1,
    text: 'Wielkoszlemowy turniej tenisowy Wimbledon rozgrywany jest na kortach:',
    answers: [
      { text: 'trawiastych', correct: true },
      { text: 'ziemnych', rival: true },
      { text: 'twardych' },
      { text: 'dywanowych' },
    ],
    note: 'Kort ziemny, czyli słynna mączka, to znak rozpoznawczy paryskiego Rolanda Garrosa — Wimbledon jako jedyny wielki szlem gra się na trawie.',
  },
  {
    id: 'kuch-tatar',
    label: 'Na surowo',
    category: 'Kuchnia',
    difficulty: 1,
    text: 'Z jakiego mięsa przyrządza się tradycyjny tatar?',
    answers: [
      { text: 'z wołowiny', correct: true },
      { text: 'z koniny', rival: true },
      { text: 'z wieprzowiny' },
      { text: 'z cielęciny' },
    ],
    note: 'Klasyczny tatar to siekana surowa polędwica wołowa, a legenda o mięsie odparzanym pod siodłem podpowiada zwodniczo koninę.',
  },
  {
    id: 'liczby-milion',
    label: 'Okrągła sumka',
    category: 'Liczby',
    difficulty: 1,
    text: 'Ile zer ma liczba milion zapisana cyframi?',
    answers: [
      { text: '6', spoken: 'sześć', correct: true },
      { text: '5', spoken: 'pięć', rival: true },
      { text: '7', spoken: 'siedem' },
      { text: '9', spoken: 'dziewięć' },
    ],
    note: 'Milion to jedynka i sześć zer, czyli tysiąc tysięcy; dziewięć zer ma dopiero miliard.',
  },
  {
    id: 'tech-android',
    label: 'Zielony ludzik',
    category: 'Technologia',
    difficulty: 1,
    text: 'Właścicielem systemu operacyjnego Android jest firma:',
    answers: [
      { text: 'Google', correct: true },
      { text: 'Samsung', rival: true },
      { text: 'Apple' },
      { text: 'Microsoft' },
    ],
    note: 'Samsung tylko instaluje Androida w swoich telefonach — system wraz z zielonym ludzikiem należy do Google’a.',
  },

  /* ========================= reszta partii ========================= */

  /* --- Geografia --- */
  {
    id: 'geo-czestochowa',
    label: 'Województwa',
    category: 'Geografia',
    difficulty: 2,
    text: 'Częstochowa leży w województwie:',
    answers: [
      { text: 'śląskim', correct: true },
      { text: 'małopolskim', rival: true },
      { text: 'łódzkim' },
      { text: 'opolskim' },
    ],
    note: 'Historycznie miasto należało do Małopolski i do 1998 roku miało własne województwo — dlatego mało kto kojarzy je ze Śląskiem.',
  },
  {
    id: 'geo-babia-gora',
    label: 'Poza konkursem',
    category: 'Geografia',
    difficulty: 2,
    text: 'Najwyższym szczytem Polski są Rysy w Tatrach. Najwyższy szczyt poza Tatrami to:',
    answers: [
      { text: 'Babia Góra', correct: true },
      { text: 'Śnieżka', rival: true },
      { text: 'Tarnica' },
      { text: 'Turbacz' },
    ],
    note: 'Babia Góra ma 1725 metrów i góruje nad Śnieżką o ponad sto metrów, choć to Śnieżka jest bardziej medialna.',
  },
  {
    id: 'geo-berno',
    label: 'Stolice Europy',
    category: 'Geografia',
    difficulty: 2,
    text: 'Stolicą Szwajcarii jest:',
    answers: [
      { text: 'Berno', correct: true },
      { text: 'Zurych', rival: true },
      { text: 'Genewa' },
      { text: 'Bazylea' },
    ],
    note: 'Zurych jest największym miastem kraju, a Genewa siedzibą organizacji międzynarodowych — ale rząd i parlament urzędują w Bernie.',
  },
  {
    id: 'geo-andaluzja',
    label: 'Flamenco',
    category: 'Geografia',
    difficulty: 3,
    text: 'Które z tych hiszpańskich miast leży w Andaluzji?',
    answers: [
      { text: 'Sewilla', correct: true },
      { text: 'Walencja', rival: true },
      { text: 'Barcelona' },
      { text: 'Madryt' },
    ],
    note: 'Pytanie dotyczy regionu, a nie sławy miasta: Walencja to Wspólnota Walencka, Barcelona — Katalonia, a Madryt leży w środku kraju.',
  },
  {
    id: 'geo-drugi-szczyt-afryki',
    label: 'Wiecznie drugi',
    category: 'Geografia',
    difficulty: 3,
    text: 'Najwyższym szczytem Afryki jest Kilimandżaro. Drugim co do wysokości jest:',
    answers: [
      { text: 'Mount Kenya', correct: true },
      { text: 'Mount Stanley', rival: true },
      { text: 'Ras Daszan' },
      { text: 'Mount Meru' },
    ],
    note: 'Mount Kenya mierzy 5199 metrów i wyprzedza o niecałe sto metrów Mount Stanley w masywie Ruwenzori.',
  },
  {
    id: 'geo-najglebsze-jezioro',
    label: 'Do dna',
    category: 'Geografia',
    difficulty: 3,
    text: 'Najgłębszym jeziorem w Polsce jest:',
    answers: [
      { text: 'Hańcza', correct: true },
      { text: 'Wigry', rival: true },
      { text: 'Śniardwy' },
      { text: 'Mamry' },
    ],
    note: 'Śniardwy są największe powierzchniowo, ale bardzo płytkie — rekord głębokości, ponad sto metrów, należy do suwalskiej Hańczy.',
  },
  {
    id: 'geo-granica-litwa',
    label: 'Miedza',
    category: 'Geografia',
    difficulty: 4,
    text: 'Z którym z tych państw Polska ma najkrótszą granicę lądową?',
    answers: [
      { text: 'Litwa', correct: true },
      { text: 'Rosja', rival: true },
      { text: 'Białoruś' },
      { text: 'Słowacja' },
    ],
    note: 'Odcinek litewski liczy około stu kilometrów — mniej niż połowę granicy z obwodem kaliningradzkim, którą wielu uważa za najkrótszą.',
  },
  {
    id: 'geo-kujawsko-pomorskie',
    label: 'Polskie miasta',
    category: 'Geografia',
    difficulty: 4,
    text: 'Które z tych miast leży w województwie kujawsko-pomorskim?',
    answers: [
      { text: 'Grudziądz', correct: true },
      { text: 'Elbląg', rival: true },
      { text: 'Piła' },
      { text: 'Słupsk' },
    ],
    note: 'Elbląg, mimo bliskości Wisły i Malborka, należy do warmińsko-mazurskiego — pytanie dotyczy podziału administracyjnego, nie geografii fizycznej.',
  },
  {
    id: 'geo-zrodla-wisly',
    label: 'Na początku',
    category: 'Geografia',
    difficulty: 5,
    text: 'Źródła Wisły znajdują się na stokach:',
    answers: [
      { text: 'Baraniej Góry', correct: true },
      { text: 'Babiej Góry', rival: true },
      { text: 'Pilska' },
      { text: 'Skrzycznego' },
    ],
    note: 'Czarna i Biała Wisełka wypływają z Baraniej Góry w Beskidzie Śląskim, a Babia Góra to najwyższy szczyt Beskidów.',
  },
  {
    id: 'geo-drugie-jezioro',
    label: 'Wicemistrz',
    category: 'Geografia',
    difficulty: 5,
    text: 'Największym jeziorem w Polsce są Śniardwy. Drugie co do powierzchni jest jezioro:',
    answers: [
      { text: 'Mamry', correct: true },
      { text: 'Łebsko', rival: true },
      { text: 'Dąbie' },
      { text: 'Jeziorak' },
    ],
    note: 'Mamry mają ponad 104 kilometry kwadratowe, Łebsko niespełna 72, więc to ono zajmuje trzecie miejsce.',
  },
  {
    id: 'geo-sejmik-kujawsko',
    label: 'Podwójna stolica',
    category: 'Geografia',
    difficulty: 5,
    text: 'Siedzibą sejmiku województwa kujawsko-pomorskiego jest:',
    answers: [
      { text: 'Toruń', correct: true },
      { text: 'Bydgoszcz', rival: true },
      { text: 'Włocławek' },
      { text: 'Grudziądz' },
    ],
    note: 'Jedno z dwóch województw o rozdzielonych stolicach — obok lubuskiego: wojewoda urzęduje w Bydgoszczy, a sejmik i marszałek w Toruniu.',
  },

  /* --- Historia --- */
  {
    id: 'hist-konstytucja',
    label: 'Majówka',
    category: 'Historia',
    difficulty: 2,
    text: 'Konstytucja Trzeciego Maja była pierwszą taką ustawą w Europie i drugą na świecie. Ta pierwsza na świecie powstała w:',
    answers: [
      { text: 'Stanach Zjednoczonych', correct: true },
      { text: 'Francji', rival: true },
      { text: 'Anglii' },
      { text: 'Holandii' },
    ],
    note: 'Amerykanie uchwalili swoją ustawę zasadniczą cztery lata wcześniej, a Francuzi — kilka miesięcy po Polakach.',
  },
  {
    id: 'hist-dwor-warszawa',
    label: 'Przeprowadzka',
    category: 'Historia',
    difficulty: 3,
    text: 'Który król przeniósł dwór królewski z Krakowa do Warszawy?',
    answers: [
      { text: 'Zygmunt III Waza', spoken: 'Zygmunt trzeci Waza', correct: true },
      { text: 'Zygmunt II August', spoken: 'Zygmunt drugi August', rival: true },
      { text: 'Stefan Batory' },
      { text: 'Władysław IV Waza', spoken: 'Władysław czwarty Waza' },
    ],
    note: 'Zygmunt August przeniósł do Warszawy obrady sejmu, ale dwór przeprowadził dopiero Zygmunt III Waza, po pożarze Wawelu.',
  },
  {
    id: 'hist-uklad-warszawski',
    label: 'Zimna wojna',
    category: 'Historia',
    difficulty: 3,
    text: 'Które z tych państw NIE należało do Układu Warszawskiego?',
    answers: [
      { text: 'Jugosławia', correct: true },
      { text: 'Rumunia', rival: true },
      { text: 'Bułgaria' },
      { text: 'Węgry' },
    ],
    note: 'Rumunia bywała w bloku krnąbrna, ale formalnie z niego nie wystąpiła — to Jugosławia po zerwaniu ze Stalinem szła własną drogą.',
  },
  {
    id: 'hist-wojna-stuletnia',
    label: 'Sto lat',
    category: 'Historia',
    difficulty: 3,
    text: 'Wojna stuletnia między Anglią a Francją trwała w rzeczywistości:',
    answers: [
      { text: '116 lat', spoken: 'sto szesnaście lat', correct: true },
      { text: '100 lat', spoken: 'sto lat', rival: true },
      { text: '99 lat', spoken: 'dziewięćdziesiąt dziewięć lat' },
      { text: '80 lat', spoken: 'osiemdziesiąt lat' },
    ],
    note: 'Nazwa to późniejsze uproszczenie historyków — konflikt ciągnął się z przerwami od 1337 do 1453 roku.',
  },
  {
    id: 'hist-koronacja-krakow',
    label: 'Koronacje',
    category: 'Historia',
    difficulty: 4,
    text: 'Który polski władca jako pierwszy koronował się w Krakowie, a nie w Gnieźnie?',
    answers: [
      { text: 'Władysław Łokietek', correct: true },
      { text: 'Kazimierz Wielki', rival: true },
      { text: 'Przemysł II', spoken: 'Przemysł drugi' },
      { text: 'Wacław II', spoken: 'Wacław drugi' },
    ],
    note: 'Łokietek przeniósł ceremonię na Wawel w 1320 roku; Kazimierz Wielki był dopiero drugim królem koronowanym w Krakowie.',
  },
  {
    id: 'hist-vasco-da-gama',
    label: 'Wielkie odkrycia',
    category: 'Historia',
    difficulty: 4,
    text: 'Krzysztof Kolumb dopłynął do Ameryki w 1492 roku. Vasco da Gama dotarł drogą morską do Indii w roku:',
    answers: [
      { text: '1498', spoken: 'tysiąc czterysta dziewięćdziesiąt osiem', correct: true },
      { text: '1488', spoken: 'tysiąc czterysta osiemdziesiąt osiem', rival: true },
      { text: '1519', spoken: 'tysiąc pięćset dziewiętnaście' },
      { text: '1522', spoken: 'tysiąc pięćset dwadzieścia dwa' },
    ],
    note: 'W 1488 roku Bartolomeu Dias opłynął jedynie Przylądek Dobrej Nadziei — do Kalikatu dotarł dopiero da Gama, dziesięć lat później.',
  },
  {
    id: 'hist-powstanie-krakowskie',
    label: 'Powstania',
    category: 'Historia',
    difficulty: 5,
    text: 'Powstanie krakowskie wybuchło w roku:',
    answers: [
      { text: '1846', spoken: 'tysiąc osiemset czterdzieści sześć', correct: true },
      { text: '1848', spoken: 'tysiąc osiemset czterdzieści osiem', rival: true },
      { text: '1830', spoken: 'tysiąc osiemset trzydzieści' },
      { text: '1863', spoken: 'tysiąc osiemset sześćdziesiąt trzy' },
    ],
    note: 'Powstanie w Wolnym Mieście Krakowie wybuchło w lutym 1846 roku, dwa lata przed Wiosną Ludów.',
  },
  {
    id: 'hist-traktat-ryski',
    label: 'Na papierze',
    category: 'Historia',
    difficulty: 5,
    text: 'Traktat kończący wojnę polsko-bolszewicką podpisano w Rydze w roku:',
    answers: [
      { text: '1921', spoken: 'tysiąc dziewięćset dwadzieścia jeden', correct: true },
      { text: '1920', spoken: 'tysiąc dziewięćset dwadzieścia', rival: true },
      { text: '1919', spoken: 'tysiąc dziewięćset dziewiętnaście' },
      { text: '1922', spoken: 'tysiąc dziewięćset dwadzieścia dwa' },
    ],
    note: 'Działania zbrojne zakończył rozejm z października 1920 roku, ale sam traktat pokojowy podpisano dopiero w marcu następnego.',
  },

  /* --- Język polski --- */
  {
    id: 'pol-groch',
    label: 'Pod ścianą',
    category: 'Język polski',
    difficulty: 2,
    text: 'Powiedzenie „rzucać grochem o ścianę” oznacza:',
    answers: [
      { text: 'mówić bez żadnego skutku', correct: true },
      { text: 'mówić bez ładu i składu', rival: true },
      { text: 'kłócić się o drobiazgi' },
      { text: 'chwalić się bez powodu' },
    ],
    note: 'Obraz jest dosłowny — groch odbija się od muru dokładnie tak, jak argumenty od kogoś, kto nie zamierza słuchać.',
  },
  {
    id: 'pol-ekwilibrystyka',
    label: 'Na linie',
    category: 'Język polski',
    difficulty: 2,
    text: 'Ekwilibrystyka to sztuka:',
    answers: [
      { text: 'utrzymywania równowagi', correct: true },
      { text: 'żonglowania przedmiotami', rival: true },
      { text: 'naśladowania głosów' },
      { text: 'tresury zwierząt' },
    ],
    note: 'Słowo pochodzi od łacińskiego aequilibrium, czyli równowaga — żonglerka to zupełnie inna specjalność cyrkowa.',
  },
  {
    id: 'pol-dolki',
    label: 'Porzekadło',
    category: 'Język polski',
    difficulty: 2,
    text: 'Przysłowie mówi: „Kto pod kim dołki kopie…”',
    answers: [
      { text: 'ten sam w nie wpada', correct: true },
      { text: 'ten sam się w nich chowa', rival: true },
      { text: 'temu ziemia się usuwa' },
      { text: 'ten prędko je zasypie' },
    ],
    note: 'Sens jest bumerangowy: intryga wraca do autora, dlatego jedyne poprawne dokończenie mówi o wpadaniu.',
  },
  {
    id: 'pol-lakoniczny',
    label: 'Krótko mówiąc',
    category: 'Język polski',
    difficulty: 3,
    text: 'Wypowiedź lakoniczna to wypowiedź:',
    answers: [
      { text: 'zwięzła', correct: true },
      { text: 'zawiła', rival: true },
      { text: 'kwiecista' },
      { text: 'szydercza' },
    ],
    note: 'Słowo pochodzi od Lakonii, czyli ziemi Spartan, słynących z odpowiadania jednym słowem.',
  },
  {
    id: 'pol-apologeta',
    label: 'Z greki',
    category: 'Język polski',
    difficulty: 3,
    text: 'Apologeta to ktoś, kto:',
    answers: [
      { text: 'gorliwie broni jakiejś idei', correct: true },
      { text: 'publicznie przeprasza za swoje słowa', rival: true },
      { text: 'zaciekle krytykuje cudze poglądy' },
      { text: 'wygłasza mowy pogrzebowe' },
    ],
    note: 'Podobieństwo do angielskiego „apology” myli — grecka „apologia” oznaczała mowę obrończą, a nie przeprosiny.',
  },
  {
    id: 'pol-dwoje-drzwi',
    label: 'Po polsku',
    category: 'Język polski',
    difficulty: 3,
    text: 'Poprawna forma to:',
    answers: [
      { text: 'dwoje drzwi', correct: true },
      { text: 'dwa drzwi', rival: true },
      { text: 'dwie drzwi' },
      { text: 'obydwa drzwi' },
    ],
    note: 'Rzeczowniki występujące tylko w liczbie mnogiej, jak drzwi, sanie czy nożyczki, łączą się z liczebnikiem zbiorowym.',
  },
  {
    id: 'pol-bednarz',
    label: 'Fach w ręku',
    category: 'Język polski',
    difficulty: 4,
    text: 'Czym zajmuje się bednarz?',
    answers: [
      { text: 'Wyrabia beczki i cebrzyki', correct: true },
      { text: 'Wyrabia koła do wozów', rival: true },
      { text: 'Kuje podkowy' },
      { text: 'Wyprawia skóry' },
    ],
    note: 'Koła robił kołodziej — obaj pracowali w drewnie, dlatego to najczęstsza pomyłka.',
  },
  {
    id: 'pol-pyrrusowe',
    label: 'Jeszcze jedno takie',
    category: 'Język polski',
    difficulty: 4,
    text: 'Określenie „pyrrusowe zwycięstwo” pochodzi od imienia:',
    answers: [
      { text: 'króla Epiru', correct: true },
      { text: 'króla Macedonii', rival: true },
      { text: 'wodza Kartaginy' },
      { text: 'cesarza Rzymu' },
    ],
    note: 'Pyrrus pokonał Rzymian pod Ausculum, tracąc kwiat swojej armii — stąd przypisywane mu zdanie o jeszcze jednym takim zwycięstwie.',
  },
  {
    id: 'pol-peryfraza',
    label: 'Nie wprost',
    category: 'Język polski',
    difficulty: 5,
    text: 'Peryfraza to inaczej:',
    answers: [
      { text: 'omówienie', correct: true },
      { text: 'przemilczenie', rival: true },
      { text: 'uosobienie' },
      { text: 'przesadnia' },
    ],
    note: 'Peryfraza zastępuje nazwę opisem („król zwierząt” zamiast „lew”), przemilczenie to elipsa, uosobienie to personifikacja, a przesadnia — hiperbola.',
  },
  {
    id: 'pol-ekspiacja',
    label: 'Mea culpa',
    category: 'Język polski',
    difficulty: 5,
    text: 'Ekspiacja to:',
    answers: [
      { text: 'odpokutowanie winy', correct: true },
      { text: 'publiczne wyznanie winy', rival: true },
      { text: 'darowanie kary' },
      { text: 'oczyszczenie z zarzutów' },
    ],
    note: 'Ekspiacja oznacza zadośćuczynienie za winę, a nie samo jej wyznanie, które jest konfesją.',
  },

  /* --- Nauka --- */
  {
    id: 'nauka-fahrenheit',
    label: 'Za oceanem',
    category: 'Nauka',
    difficulty: 2,
    text: 'W skali Fahrenheita woda zamarza w temperaturze:',
    answers: [
      { text: '32 stopni', spoken: 'trzydziestu dwóch stopni', correct: true },
      { text: '0 stopni', spoken: 'zera stopni', rival: true },
      { text: '100 stopni', spoken: 'stu stopni' },
      { text: '212 stopni', spoken: 'dwustu dwunastu stopni' },
    ],
    note: '212 stopni Fahrenheita to punkt wrzenia, a zero w tej skali odpowiada mniej więcej minus osiemnastu stopniom Celsjusza.',
  },
  {
    id: 'nauka-potas',
    label: 'Tablica',
    category: 'Nauka',
    difficulty: 2,
    text: 'Symbolem K oznacza się w chemii:',
    answers: [
      { text: 'potas', correct: true },
      { text: 'krzem', rival: true },
      { text: 'kobalt' },
      { text: 'krypton' },
    ],
    note: 'Symbol pochodzi od łacińskiego kalium, a nie od polskiej nazwy — krzem to Si, kobalt Co, krypton Kr.',
  },
  {
    id: 'nauka-najwiekszy-narzad',
    label: 'Anatomia',
    category: 'Nauka',
    difficulty: 3,
    text: 'Największym narządem ludzkiego ciała jest:',
    answers: [
      { text: 'skóra', correct: true },
      { text: 'wątroba', rival: true },
      { text: 'płuca' },
      { text: 'jelito cienkie' },
    ],
    note: 'Wątroba jest największym narządem wewnętrznym, ale skóra bije ją i masą, i powierzchnią.',
  },
  {
    id: 'nauka-kat-pieciokat',
    label: 'Pentagon',
    category: 'Nauka',
    difficulty: 4,
    text: 'Ile stopni ma kąt wewnętrzny w pięciokącie foremnym?',
    answers: [
      { text: '108', spoken: 'sto osiem', correct: true },
      { text: '120', spoken: 'sto dwadzieścia', rival: true },
      { text: '90', spoken: 'dziewięćdziesiąt' },
      { text: '144', spoken: 'sto czterdzieści cztery' },
    ],
    note: '120 stopni to kąt w sześciokącie, a 144 — w dziesięciokącie; w pięciokącie suma kątów wynosi 540 stopni.',
  },
  {
    id: 'nauka-symbol-w',
    label: 'Pierwiastki',
    category: 'Nauka',
    difficulty: 5,
    text: 'Pierwiastek chemiczny o symbolu „W” to:',
    answers: [
      { text: 'wolfram', correct: true },
      { text: 'wanad', rival: true },
      { text: 'wapń' },
      { text: 'węgiel' },
    ],
    note: 'Polskie nazwy mylą trop: wanad ma symbol V, wapń Ca, a węgiel C — literę W nosi wyłącznie wolfram.',
  },
  {
    id: 'nauka-najkrotsza-doba',
    label: 'Planety',
    category: 'Nauka',
    difficulty: 5,
    text: 'Najkrótszą dobę spośród planet Układu Słonecznego ma:',
    answers: [
      { text: 'Jowisz', correct: true },
      { text: 'Saturn', rival: true },
      { text: 'Uran' },
      { text: 'Neptun' },
    ],
    note: 'Największa planeta obraca się najszybciej — doba Jowisza trwa niespełna dziesięć godzin, Saturna nieco ponad dziesięć.',
  },

  /* --- Przyroda --- */
  {
    id: 'przyr-jez',
    label: 'Do wiosny',
    category: 'Przyroda',
    difficulty: 2,
    text: 'Które z tych zwierząt zapada w prawdziwy sen zimowy?',
    answers: [
      { text: 'jeż', correct: true },
      { text: 'niedźwiedź brunatny', rival: true },
      { text: 'borsuk' },
      { text: 'wilk' },
    ],
    note: 'Niedźwiedź tylko drzemie — jego temperatura spada nieznacznie i potrafi się obudzić, podczas gdy jeż wychładza się niemal do temperatury otoczenia.',
  },
  {
    id: 'przyr-nie-gryzon',
    label: 'Czarna owca',
    category: 'Przyroda',
    difficulty: 3,
    text: 'Które z tych zwierząt NIE jest gryzoniem?',
    answers: [
      { text: 'zając', correct: true },
      { text: 'bóbr', rival: true },
      { text: 'wiewiórka' },
      { text: 'szczur' },
    ],
    note: 'Bóbr mimo rozmiarów jest gryzoniem, a zające i króliki tworzą osobny rząd zajęczaków, z dodatkową parą siekaczy w szczęce.',
  },
  {
    id: 'przyr-osmiornica',
    label: 'Serce nie sługa',
    category: 'Przyroda',
    difficulty: 3,
    text: 'Ile serc ma ośmiornica?',
    answers: [
      { text: '3', spoken: 'trzy', correct: true },
      { text: '2', spoken: 'dwa', rival: true },
      { text: '1', spoken: 'jedno' },
      { text: '8', spoken: 'osiem' },
    ],
    note: 'Dwa serca tłoczą krew przez skrzela, a trzecie, główne, rozprowadza ją po reszcie ciała — liczba ramion nie ma z tym nic wspólnego.',
  },
  {
    id: 'przyr-najwiekszy-park',
    label: 'Parki narodowe',
    category: 'Przyroda',
    difficulty: 5,
    text: 'Największym powierzchniowo parkiem narodowym w Polsce jest park:',
    answers: [
      { text: 'Biebrzański', correct: true },
      { text: 'Kampinoski', rival: true },
      { text: 'Bieszczadzki' },
      { text: 'Tatrzański' },
    ],
    note: 'Bagna nad Biebrzą zajmują blisko 600 kilometrów kwadratowych, znacznie więcej niż Kampinos, Bieszczady czy Tatry.',
  },

  /* --- Kultura --- */
  {
    id: 'kult-czardasz',
    label: 'Na parkiecie',
    category: 'Kultura',
    difficulty: 2,
    text: 'Który z tych tańców NIE należy do polskich tańców narodowych?',
    answers: [
      { text: 'czardasz', correct: true },
      { text: 'oberek', rival: true },
      { text: 'kujawiak' },
      { text: 'mazur' },
    ],
    note: 'Polskich tańców narodowych jest pięć: polonez, krakowiak, mazur, kujawiak i oberek — czardasz przyjechał z Węgier.',
  },
  {
    id: 'kult-unesco-1978',
    label: 'Dziedzictwo',
    category: 'Kultura',
    difficulty: 3,
    text: 'Na pierwszej liście światowego dziedzictwa UNESCO znalazły się dwa polskie obiekty: Stare Miasto w Krakowie oraz:',
    answers: [
      { text: 'kopalnia soli w Wieliczce', correct: true },
      { text: 'Puszcza Białowieska', rival: true },
      { text: 'zamek krzyżacki w Malborku' },
      { text: 'Stare Miasto w Zamościu' },
    ],
    note: 'Wieliczka trafiła na listę w 1978 roku, w gronie zaledwie dwunastu pierwszych obiektów świata; Białowieżę wpisano rok później.',
  },
  {
    id: 'kult-didaskalia',
    label: 'Między wierszami',
    category: 'Kultura',
    difficulty: 4,
    text: 'Czym są didaskalia w tekście dramatu?',
    answers: [
      { text: 'Uwagi autora dotyczące gry aktorów i sceny', correct: true },
      { text: 'Opis dekoracji przygotowany przez scenografa', rival: true },
      { text: 'Monolog bohatera kierowany do widowni' },
      { text: 'Przerwa między aktami' },
    ],
    note: 'Didaskalia pisze autor i drukuje się je zwykle kursywą — scenograf dopiero z nich korzysta.',
  },
  {
    id: 'kult-szal-uniesien',
    label: 'Skandal',
    category: 'Kultura',
    difficulty: 5,
    text: 'Autorem obrazu „Szał uniesień” jest:',
    answers: [
      { text: 'Władysław Podkowiński', correct: true },
      { text: 'Jacek Malczewski', rival: true },
      { text: 'Józef Mehoffer' },
      { text: 'Leon Wyczółkowski' },
    ],
    note: 'Podkowiński namalował „Szał uniesień” w 1894 roku i sam pociął go nożem na własnej wystawie.',
  },
  {
    id: 'kult-grunwald-matejki',
    label: 'Duży format',
    category: 'Kultura',
    difficulty: 5,
    text: '„Bitwa pod Grunwaldem” Jana Matejki znajduje się w Muzeum Narodowym w:',
    answers: [
      { text: 'Warszawie', correct: true },
      { text: 'Krakowie', rival: true },
      { text: 'Poznaniu' },
      { text: 'Wrocławiu' },
    ],
    note: 'Choć Matejko był krakowianinem, jego największe płótno wisi w Warszawie — w Krakowie pozostał „Hołd pruski”.',
  },

  /* --- Film --- */
  {
    id: 'film-pierwsza-animacja',
    label: 'Kreskówki',
    category: 'Film',
    difficulty: 3,
    text: 'Pierwszym pełnometrażowym filmem animowanym wytwórni Disneya była:',
    answers: [
      { text: '„Królewna Śnieżka i siedmiu krasnoludków”', correct: true },
      { text: '„Pinokio”', rival: true },
      { text: '„Fantazja”' },
      { text: '„Bambi”' },
    ],
    note: 'Śnieżka weszła na ekrany w 1937 roku, trzy lata przed „Pinokiem” i „Fantazją”.',
  },
  {
    id: 'film-polski-oscar',
    label: 'Polskie kino',
    category: 'Film',
    difficulty: 3,
    text: 'Który polski film jako pierwszy zdobył Oscara w kategorii najlepszy film nieanglojęzyczny?',
    answers: [
      { text: '„Ida”', correct: true },
      { text: '„Pianista”', rival: true },
      { text: '„Zimna wojna”' },
      { text: '„Katyń”' },
    ],
    note: '„Pianista” przyniósł statuetki za reżyserię, scenariusz i główną rolę męską, ale w kategorii filmu nieanglojęzycznego pierwsza była dopiero „Ida”.',
  },
  {
    id: 'film-rejs',
    label: 'Na wodzie',
    category: 'Film',
    difficulty: 5,
    text: 'Reżyserem komedii „Rejs” był:',
    answers: [
      { text: 'Marek Piwowski', correct: true },
      { text: 'Stanisław Bareja', rival: true },
      { text: 'Andrzej Kondratiuk' },
      { text: 'Sylwester Chęciński' },
    ],
    note: 'Pułapką jest podobna poetyka absurdu — „Rejs” nakręcił Piwowski, a Bareja odpowiada za „Misia”.',
  },
  {
    id: 'film-saragossa',
    label: 'Ekranizacje',
    category: 'Film',
    difficulty: 5,
    text: 'Film „Rękopis znaleziony w Saragossie” wyreżyserował:',
    answers: [
      { text: 'Wojciech Jerzy Has', correct: true },
      { text: 'Jerzy Kawalerowicz', rival: true },
      { text: 'Andrzej Munk' },
      { text: 'Tadeusz Konwicki' },
    ],
    note: 'Has zekranizował powieść Jana Potockiego, a Kawalerowicz z tego samego pokolenia nakręcił „Matkę Joannę od Aniołów”.',
  },

  /* --- Muzyka --- */
  {
    id: 'muz-chopin',
    label: 'Sercem i ciałem',
    category: 'Muzyka',
    difficulty: 2,
    text: 'Serce Fryderyka Chopina spoczywa w warszawskim kościele Świętego Krzyża. Jego ciało pochowano w:',
    answers: [
      { text: 'Paryżu', correct: true },
      { text: 'Żelazowej Woli', rival: true },
      { text: 'Wiedniu' },
      { text: 'Londynie' },
    ],
    note: 'Kompozytor zmarł w Paryżu i leży na cmentarzu Père-Lachaise; do kraju wróciło tylko serce, przewiezione potajemnie przez jego siostrę.',
  },
  {
    id: 'muz-saksofon',
    label: 'Dęta sprawa',
    category: 'Muzyka',
    difficulty: 3,
    text: 'Który z tych instrumentów zalicza się do dętych drewnianych?',
    answers: [
      { text: 'saksofon', correct: true },
      { text: 'waltornia', rival: true },
      { text: 'trąbka' },
      { text: 'puzon' },
    ],
    note: 'O przynależności decyduje sposób wydobycia dźwięku, a nie materiał: saksofon jest z metalu, lecz gra się na nim drewnianym stroikiem.',
  },
  {
    id: 'muz-mazurek',
    label: 'Symbole narodowe',
    category: 'Muzyka',
    difficulty: 3,
    text: 'Słowa „Mazurka Dąbrowskiego” powstały:',
    answers: [
      { text: 'we Włoszech', correct: true },
      { text: 'we Francji', rival: true },
      { text: 'w Polsce' },
      { text: 'w Rosji' },
    ],
    note: 'Józef Wybicki napisał pieśń dla Legionów stacjonujących w Reggio nell’Emilia — stąd w tekście mowa o powrocie z ziemi włoskiej.',
  },
  {
    id: 'muz-konkurs-chopinowski',
    label: 'Terminarz',
    category: 'Muzyka',
    difficulty: 4,
    text: 'Międzynarodowy Konkurs Pianistyczny imienia Fryderyka Chopina odbywa się:',
    answers: [
      { text: 'co 5 lat', spoken: 'co pięć lat', correct: true },
      { text: 'co 4 lata', spoken: 'co cztery lata', rival: true },
      { text: 'co 3 lata', spoken: 'co trzy lata' },
      { text: 'co 2 lata', spoken: 'co dwa lata' },
    ],
    note: 'Pięcioletni rytm przyjęto już przy pierwszym konkursie w 1927 roku; przerwała go wojna, a ostatnio pandemia, przez którą osiemnastą edycję przesunięto z 2020 na 2021 rok.',
  },
  {
    id: 'muz-harnasie',
    label: 'Balet',
    category: 'Muzyka',
    difficulty: 5,
    text: 'Autorem baletu „Harnasie” jest:',
    answers: [
      { text: 'Karol Szymanowski', correct: true },
      { text: 'Ludomir Różycki', rival: true },
      { text: 'Mieczysław Karłowicz' },
      { text: 'Stanisław Moniuszko' },
    ],
    note: 'Góralskie „Harnasie” napisał Szymanowski, natomiast Różyckiego kojarzy się z baletem „Pan Twardowski”.',
  },
  {
    id: 'muz-kocham-cie',
    label: 'Polski rock',
    category: 'Muzyka',
    difficulty: 5,
    text: 'Piosenkę „Kocham cię, kochanie moje” nagrał zespół:',
    answers: [
      { text: 'Maanam', correct: true },
      { text: 'Republika', rival: true },
      { text: 'Lady Pank' },
      { text: 'Lombard' },
    ],
    note: 'Utwór z muzyką Marka Jackowskiego i tekstem Kory ukazał się w 1983 roku jako singiel Tonpressu — nigdy nie trafił na żadną płytę studyjną zespołu.',
  },

  /* --- Sport --- */
  {
    id: 'sport-set',
    label: 'Nad siatką',
    category: 'Sport',
    difficulty: 2,
    text: 'Zwykłego seta w siatkówce wygrywa drużyna, która zdobędzie co najmniej:',
    answers: [
      { text: '25 punktów', spoken: 'dwadzieścia pięć punktów', correct: true },
      { text: '15 punktów', spoken: 'piętnaście punktów', rival: true },
      { text: '21 punktów', spoken: 'dwadzieścia jeden punktów' },
      { text: '30 punktów', spoken: 'trzydzieści punktów' },
    ],
    note: 'Do piętnastu grano przed zmianą przepisów pod koniec lat dziewięćdziesiątych — dziś tyle liczy się już tylko w tie-breaku.',
  },
  {
    id: 'sport-chamonix',
    label: 'Zimowe igrzyska',
    category: 'Sport',
    difficulty: 2,
    text: 'Pierwsze zimowe igrzyska olimpijskie odbyły się we Francji, w miejscowości:',
    answers: [
      { text: 'Chamonix', correct: true },
      { text: 'Grenoble', rival: true },
      { text: 'Albertville' },
      { text: 'Lyon' },
    ],
    note: 'Chamonix gościło sportowców w 1924 roku, Grenoble dopiero czterdzieści cztery lata później, a Lyon nigdy.',
  },
  {
    id: 'sport-grochy',
    label: 'Pod górkę',
    category: 'Sport',
    difficulty: 3,
    text: 'W Tour de France koszulkę w czerwone grochy nosi lider klasyfikacji:',
    answers: [
      { text: 'górskiej', correct: true },
      { text: 'punktowej', rival: true },
      { text: 'młodzieżowej' },
      { text: 'drużynowej' },
    ],
    note: 'Klasyfikacja punktowa ma koszulkę zieloną, a najlepszy młodzieżowiec jedzie w białej.',
  },
  {
    id: 'sport-1500',
    label: 'Bieżnia',
    category: 'Sport',
    difficulty: 3,
    text: 'Ile okrążeń standardowej stadionowej bieżni liczy bieg na 1500 metrów?',
    answers: [
      { text: '3,75', spoken: 'trzy i trzy czwarte', correct: true },
      { text: '4', spoken: 'cztery', rival: true },
      { text: '3,5', spoken: 'trzy i pół' },
      { text: '5', spoken: 'pięć' },
    ],
    note: 'Okrążenie ma 400 metrów, więc do pełnych czterech brakuje stu — biegacze startują z linii na początku przeciwległej prostej.',
  },
  {
    id: 'sport-siatkowka-1974',
    label: 'Rocznice',
    category: 'Sport',
    difficulty: 4,
    text: 'W którym roku polscy siatkarze po raz pierwszy zostali mistrzami świata?',
    answers: [
      { text: '1974', spoken: 'tysiąc dziewięćset siedemdziesiąt cztery', correct: true },
      { text: '1976', spoken: 'tysiąc dziewięćset siedemdziesiąt sześć', rival: true },
      { text: '1972', spoken: 'tysiąc dziewięćset siedemdziesiąt dwa' },
      { text: '1978', spoken: 'tysiąc dziewięćset siedemdziesiąt osiem' },
    ],
    note: 'W 1976 roku w Montrealu Polacy sięgnęli po złoto olimpijskie — tytuł mistrzów świata zdobyli dwa lata wcześniej w Meksyku.',
  },
  {
    id: 'sport-fortuna',
    label: 'Fortuna kołem',
    category: 'Sport',
    difficulty: 5,
    text: 'Wojciech Fortuna zdobył olimpijskie złoto w skokach narciarskich w roku:',
    answers: [
      { text: '1972', spoken: 'tysiąc dziewięćset siedemdziesiąt dwa', correct: true },
      { text: '1976', spoken: 'tysiąc dziewięćset siedemdziesiąt sześć', rival: true },
      { text: '1968', spoken: 'tysiąc dziewięćset sześćdziesiąt osiem' },
      { text: '1980', spoken: 'tysiąc dziewięćset osiemdziesiąt' },
    ],
    note: 'Fortuna wygrał konkurs na dużej skoczni w Sapporo, zdobywając pierwsze polskie złoto zimowych igrzysk.',
  },
  {
    id: 'sport-siatka-wysokosc',
    label: 'Wysoko zawieszona',
    category: 'Sport',
    difficulty: 5,
    text: 'Na jakiej wysokości zawieszona jest siatka w meczu siatkówki mężczyzn?',
    answers: [
      { text: '2,43 m', spoken: 'dwa metry i czterdzieści trzy centymetry', correct: true },
      { text: '2,24 m', spoken: 'dwa metry i dwadzieścia cztery centymetry', rival: true },
      { text: '2,35 m', spoken: 'dwa metry i trzydzieści pięć centymetrów' },
      { text: '2,50 m', spoken: 'dwa metry i pięćdziesiąt centymetrów' },
    ],
    note: 'Dwa metry czterdzieści trzy to norma męska, a dwa metry dwadzieścia cztery — kobieca.',
  },

  /* --- Kuchnia --- */
  {
    id: 'kuch-zur',
    label: 'Na kwaśno',
    category: 'Kuchnia',
    difficulty: 2,
    text: 'Zakwas na tradycyjny żur przygotowuje się z mąki:',
    answers: [
      { text: 'żytniej', correct: true },
      { text: 'pszennej', rival: true },
      { text: 'gryczanej' },
      { text: 'jęczmiennej' },
    ],
    note: 'To rodzaj mąki odróżnia obie zupy: żur stoi na życie, a barszcz biały na pszenicy.',
  },
  {
    id: 'kuch-jaglana',
    label: 'Ziarno',
    category: 'Kuchnia',
    difficulty: 3,
    text: 'Kaszę jaglaną otrzymuje się z ziaren:',
    answers: [
      { text: 'prosa', correct: true },
      { text: 'jęczmienia', rival: true },
      { text: 'gryki' },
      { text: 'pszenicy' },
    ],
    note: 'Myli podobieństwo nazw do kaszy jęczmiennej — z jęczmienia są pęczak i perłowa, z gryki gryczana, a z pszenicy manna.',
  },
  {
    id: 'kuch-balsamiczny',
    label: 'Kwaśna sprawa',
    category: 'Kuchnia',
    difficulty: 4,
    text: 'Z czego powstaje tradycyjny ocet balsamiczny z Modeny?',
    answers: [
      { text: 'z gotowanego moszczu winogronowego', correct: true },
      { text: 'z czerwonego wina', rival: true },
      { text: 'ze sfermentowanych jabłek' },
      { text: 'z ryżu' },
    ],
    note: 'Do tradycyjnego balsamico nie dolewa się ani wina, ani octu winnego — zagęszczony, gotowany moszcz fermentuje sam i dojrzewa latami w kolejnych beczkach.',
  },
  {
    id: 'kuch-szafran',
    label: 'Na wagę złota',
    category: 'Kuchnia',
    difficulty: 4,
    text: 'Która z tych przypraw pochodzi z kwiatu?',
    answers: [
      { text: 'szafran', correct: true },
      { text: 'kardamon', rival: true },
      { text: 'cynamon' },
      { text: 'imbir' },
    ],
    note: 'Szafran to suszone znamiona słupków krokusa, kardamon pochodzi z owocu, cynamon z kory, a imbir z kłącza.',
  },
  {
    id: 'kuch-negroni',
    label: 'Gorzka prawda',
    category: 'Kuchnia',
    difficulty: 5,
    text: 'Obok ginu i czerwonego wermutu trzecim składnikiem koktajlu negroni jest:',
    answers: [
      { text: 'Campari', correct: true },
      { text: 'Aperol', rival: true },
      { text: 'Cynar' },
      { text: 'Amaro Averna' },
    ],
    note: 'Klasyczne negroni to równe części ginu, czerwonego wermutu i Campari — z Aperolem powstaje inny, łagodniejszy drink.',
  },

  /* --- Literatura --- */
  {
    id: 'lit-pan-tadeusz',
    label: 'Z tęsknoty',
    category: 'Literatura',
    difficulty: 2,
    text: 'Adam Mickiewicz napisał „Pana Tadeusza” w:',
    answers: [
      { text: 'Paryżu', correct: true },
      { text: 'Wilnie', rival: true },
      { text: 'Nowogródku' },
      { text: 'Rzymie' },
    ],
    note: 'Epopeja powstała na emigracji w latach trzydziestych XIX wieku — opisywanych stron poeta nie oglądał już od dziesięciu lat.',
  },
  {
    id: 'lit-nobel-pierwszy',
    label: 'Nagrody',
    category: 'Literatura',
    difficulty: 2,
    text: 'Pierwszym Polakiem uhonorowanym Literacką Nagrodą Nobla był:',
    answers: [
      { text: 'Henryk Sienkiewicz', correct: true },
      { text: 'Władysław Reymont', rival: true },
      { text: 'Czesław Miłosz' },
      { text: 'Wisława Szymborska' },
    ],
    note: 'Sienkiewicz odebrał nagrodę w 1905 roku, głównie dzięki „Quo vadis”; Reymont za „Chłopów” dopiero dziewiętnaście lat później.',
  },
  {
    id: 'lit-nie-mickiewicz',
    label: 'Lektury',
    category: 'Literatura',
    difficulty: 3,
    text: 'Który z tych utworów NIE wyszedł spod pióra Adama Mickiewicza?',
    answers: [
      { text: '„Kordian”', correct: true },
      { text: '„Grażyna”', rival: true },
      { text: '„Dziady”' },
      { text: '„Konrad Wallenrod”' },
    ],
    note: '„Kordian” to odpowiedź Juliusza Słowackiego na „Dziady”, przez co bywa mylnie przypisywany Mickiewiczowi.',
  },
  {
    id: 'lit-rosyjscy-noblisci',
    label: 'Nobliści',
    category: 'Literatura',
    difficulty: 5,
    text: 'Który z tych rosyjskich pisarzy NIE otrzymał literackiej Nagrody Nobla?',
    answers: [
      { text: 'Lew Tołstoj', correct: true },
      { text: 'Michaił Szołochow', rival: true },
      { text: 'Iwan Bunin' },
      { text: 'Aleksander Sołżenicyn' },
    ],
    note: 'Tołstoj był wielokrotnie nominowany, ale nigdy nie dostał nagrody — Bunin, Szołochow i Sołżenicyn ją otrzymali.',
  },

  /* --- Liczby --- */
  {
    id: 'liczby-pierwsza',
    label: 'Nie do podziału',
    category: 'Liczby',
    difficulty: 3,
    text: 'Która z tych liczb jest liczbą pierwszą?',
    answers: [
      { text: '97', spoken: 'dziewięćdziesiąt siedem', correct: true },
      { text: '91', spoken: 'dziewięćdziesiąt jeden', rival: true },
      { text: '87', spoken: 'osiemdziesiąt siedem' },
      { text: '51', spoken: 'pięćdziesiąt jeden' },
    ],
    note: 'Pozostałe tylko wyglądają na pierwsze: 91 to 7 razy 13, a 87 i 51 dzielą się przez 3.',
  },
  {
    id: 'liczby-bilion',
    label: 'Do potęgi',
    category: 'Liczby',
    difficulty: 5,
    text: 'Ile zer ma bilion zapisany zgodnie z polskim nazewnictwem liczb?',
    answers: [
      { text: '12', spoken: 'dwanaście', correct: true },
      { text: '9', spoken: 'dziewięć', rival: true },
      { text: '15', spoken: 'piętnaście' },
      { text: '18', spoken: 'osiemnaście' },
    ],
    note: 'W polskiej skali długiej bilion to milion milionów, a nie angielski „billion” z dziewięcioma zerami.',
  },

  /* --- Technologia --- */
  {
    id: 'tech-megabajt',
    label: 'Okrągła liczba',
    category: 'Technologia',
    difficulty: 3,
    text: 'W klasycznym, binarnym przeliczeniu jeden megabajt to:',
    answers: [
      { text: '1024 kilobajty', spoken: 'tysiąc dwadzieścia cztery kilobajty', correct: true },
      { text: '1000 kilobajtów', spoken: 'tysiąc kilobajtów', rival: true },
      { text: '512 kilobajtów', spoken: 'pięćset dwanaście kilobajtów' },
      { text: '2048 kilobajtów', spoken: 'dwa tysiące czterdzieści osiem kilobajtów' },
    ],
    note: 'Komputery liczą potęgami dwójki, a dwa do dziesiątej to właśnie 1024 — okrągły tysiąc jest wygodnym przybliżeniem producentów dysków.',
  },
  {
    id: 'tech-najstarszy-jezyk',
    label: 'Języki programowania',
    category: 'Technologia',
    difficulty: 4,
    text: 'Który z tych języków programowania powstał najwcześniej?',
    answers: [
      { text: 'Fortran', correct: true },
      { text: 'COBOL', rival: true },
      { text: 'Pascal' },
      { text: 'C' },
    ],
    note: 'Fortran wyprzedził COBOL o dwa lata i oba są starsze od Pascala i C o całe pokolenie sprzętu.',
  },
  {
    id: 'tech-java-firma',
    label: 'Mała czarna',
    category: 'Technologia',
    difficulty: 5,
    text: 'Język programowania Java powstał w firmie:',
    answers: [
      { text: 'Sun Microsystems', correct: true },
      { text: 'Netscape', rival: true },
      { text: 'Borland' },
      { text: 'IBM' },
    ],
    note: 'Zespół Jamesa Goslinga stworzył Javę w Sun Microsystems, a Netscape odpowiada za mylnie kojarzony z nią JavaScript.',
  },
];

export default QUESTIONS;
